# Return forecasts generated by the default model
#' @title Generate forecasts for the default submodel model. Other submodels have a separate function.
#'
#' @description
#' \code{PredictDflt} Generate default forecasts based on indicative data from a data frame.
#' The forecasts are added as columns to the data frame. Other submodels are driven by PredictSubmodel.
#'
#' @param d60.spl Spline coefficients for d60ent loans
#' @param delq.spl Spline coefficients for delinquent loans
#' @param data data frame containing indicative data for the loans/pools/replines that we want projections for
#' @param version Model version. Allows flexibility in changing model specifications for different versions.
#'
#' @return
#' List with submodel predictions
#'
#' @examples
#' \dontrun{
#'  PredictDflt(d60.spl=d60.spl, delq.spl=NA, data=ppdata, version="v4.00")
#'  }
#'
PredictDflt <- function(d0.spl = NA, d30.spl=NA, d60.spl=NA, d90.spl=NA, cure.spl=NA, buyout.spl=NA, test = FALSE, data, version="") {
  if (! any(is.na(d0.spl)) ) {
    start_time2 <- Sys.time()
    cat("running d0 mdl", "\n")

    pickD0 = ifelse(data$delMonths == 0, 1, 0)
    d0.seasonals <- SeasonalAdjustment(seasonals = d0.spl$seasonalityMultipliers, months = data$monthBucket)
    d0.mdr <- rep(d0.spl$baselineConstant, times=nrow(data)) * d0.seasonals * d0.spl$adjustmentFactor
    param.d0 <- names(d0.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp"), names(d0.spl))]
    d0.mdr.status <- data.frame(matrix(1, nrow = nrow(data), ncol = 4))
    names(d0.mdr.status) <- param.d0
    d0.mult.df <- data.frame(matrix(1, nrow = nrow(data), ncol = 2))
    names(d0.mult.df) <- c("cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp")

    # get cumHpi index
    a <- unlist(d0.spl["cumHpiIndexInterp"][[1]][1])
    b <- unlist(d0.spl["cumHpiIndexInterp"][[1]][2])
    x <- data$fico
    d0.mult.df[, "cumHpiIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d0.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][1])
    b <- unlist(d0.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][2])
    x <- data$fico
    d0.mult.df[, "laggedUnemployChangeSinceStatusIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y


    for (q in param.d0) {
      d0.spl.status  <- d0.spl[[q]]


      if (q == 'none'){
        param.d0.status <- names(d0.spl.status)[-match(c("noFico", "noDti"),
                                                       names(d0.spl.status))]
      }
      else{
        param.d0.status <- names(d0.spl.status)[-match(c("noFico"),
                                                       names(d0.spl.status))]
      }

      # add data frame for multiplier
      for (p in param.d0.status) {
        #cat(q, p, "\n")        
        idx <- match(p, names(d0.spl.status))
        # don't need to interpolate
        if (p != "cumHpi" & p != "laggedUnemployChangeSinceStatus"){
          a <- unlist(d0.spl.status[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
          b <- unlist(d0.spl.status[idx][[1]][2])
          x <- data[[p]]
          d0.mult.status <- BuildSpline(a=a, b=b, x=x)$y
          if (p == 'dti'){
            d0.mult.status <- ifelse(data$dti == -999, d0.spl.status$noDti, d0.mult.status)
          }
          if (p == "fico"){
            d0.mult.status <- ifelse(data$hasFICOFlag == 0, d0.spl.status$noFico, d0.mult.status)
          }
        }
        # need to interpolate
        else{
          interp = d0.spl.status[p][[1]]$interpAttribute
          n <- length(d0.spl.status[p][[1]]$functions)
          y <- rep(0, times = nrow(data))
          wgt <- rep(0, times = nrow(data))
          interpIdx = d0.mult.df[, interp]
          tmp = rep(0, times = nrow(data))

          a <- unlist(d0.spl.status[p][[1]]$functions[[1]][1])
          b <- unlist(d0.spl.status[p][[1]]$functions[[1]][2])
          x <- data[[p]]
          noFICO <- BuildSpline(a=a, b=b, x=x)$y

          for (i in 2: n){
            a <- unlist(d0.spl.status[p][[1]]$functions[[i]][1])
            b <- unlist(d0.spl.status[p][[1]]$functions[[i]][2])
            x <- data[[p]]
            y <- BuildSpline(a=a, b=b, x=x)$y
            wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
            tmp = tmp + y * wgt
          }
          d0.mult.status <- tmp
          d0.mult.status <- ifelse(data$hasFICOFlag == 1, d0.mult.status, noFICO)
        }
        d0.mdr.status[[q]] <- d0.mdr.status[[q]] * d0.mult.status
        if (test){
            mult = paste("d0", q, p, sep = "_")
            if (q == "reperf"){
                pickStatus = paste("pct", "rp", sep = "_") 
            }
            else if (q == "hampMod"){
                pickStatus = paste("pct", "hmod", sep = "_") 
            }
            else if (q == "nonHampMod"){
                pickStatus = paste("pct", "nhmod", sep = "_") 
            }
            else{
                pickStatus = paste("pct", "none", sep = "_") 
            }
            d0.mult.df[[mult]] = d0.mult.status * data[[pickStatus]] * 0.01 * pickD0
        }
      }
    }
    d0.mdr = d0.mdr * 0.01 * (d0.mdr.status$none*data$pct_none + d0.mdr.status$reperf*data$pct_rp + d0.mdr.status$hampMod*data$pct_hmod + d0.mdr.status$nonHampMod*data$pct_nhmod) * pickD0
    
    if (!test){
        rm(d0.mult.df, d0.mult.status)    
    }
    
    end_time2 <- Sys.time()
    cat("d0 ", difftime(end_time2, start_time2, units = "mins"), "\n")

  } else {
    d0.mdr <- NA
  }

  if (! any(is.na(d30.spl)) ) {
    start_time3 <- Sys.time()

    cat("running d30 mdl", "\n")

    pickD30 = ifelse(data$delMonths == 1, 1, 0)
    d30.seasonals <- SeasonalAdjustment(seasonals = d30.spl$seasonalityMultipliers, months = data$monthBucket)
    d30.mdr <- rep(d30.spl$baselineConstant, times=nrow(data)) * d30.seasonals * d30.spl$adjustmentFactor
    param.d30 <- names(d30.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp"), names(d30.spl))]
    d30.mdr.status <- data.frame(matrix(1, nrow = nrow(data), ncol = 4))
    names(d30.mdr.status) <- param.d30
    d30.mult.df <- data.frame(matrix(1, nrow = nrow(data), ncol = 2))
    names(d30.mult.df) <- c("cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp")

    # get cumHpi index
    a <- unlist(d30.spl["cumHpiIndexInterp"][[1]][1])
    b <- unlist(d30.spl["cumHpiIndexInterp"][[1]][2])
    x <- data$fico
    d30.mult.df[, "cumHpiIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d30.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][1])
    b <- unlist(d30.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][2])
    x <- data$fico
    d30.mult.df[, "laggedUnemployChangeSinceStatusIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y

    for (q in param.d30) {
      d30.spl.status  <- d30.spl[[q]]
      d30.mult.status <- rep(1, times=nrow(data))

      if (q == 'none'){
        param.d30.status <- names(d30.spl.status)[-match(c("noFico", "noDti"),
                                                         names(d30.spl.status))]
      }
      else{
        param.d30.status <- names(d30.spl.status)[-match(c("noFico"),
                                                         names(d30.spl.status))]
      }

      # add data frame for multiplier
      for (p in param.d30.status) { 
        #cat(q, p, "\n")      
        idx <- match(p, names(d30.spl.status))
        # don't need to interpolate
        if (p != "cumHpi" & p != "laggedUnemployChangeSinceStatus"){
          a <- unlist(d30.spl.status[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
          b <- unlist(d30.spl.status[idx][[1]][2])
          x <- data[[p]]
          d30.mult.status <- BuildSpline(a=a, b=b, x=x)$y
          if (p == 'dti'){
            d30.mult.status <- ifelse(data$dti == -999, d30.spl.status$noDti, d30.mult.status)
          }
          if (p == "fico"){
            d30.mult.status <- ifelse(data$hasFICOFlag == 0, d30.spl.status$noFico, d30.mult.status)
          }
        }
        # need to interpolate
        else{
          interp = d30.spl.status[p][[1]]$interpAttribute
          n <- length(d30.spl.status[p][[1]]$functions)
          y <- rep(0, times = nrow(data))
          wgt <- rep(0, times = nrow(data))
          interpIdx = d30.mult.df[, interp]
          tmp = rep(0, times = nrow(data))

          a <- unlist(d30.spl.status[p][[1]]$functions[[1]][1])
          b <- unlist(d30.spl.status[p][[1]]$functions[[1]][2])
          x <- data[[p]]
          noFICO <- BuildSpline(a=a, b=b, x=x)$y

          for (i in 2: n){
            a <- unlist(d30.spl.status[p][[1]]$functions[[i]][1])
            b <- unlist(d30.spl.status[p][[1]]$functions[[i]][2])
            x <- data[[p]]
            y <- BuildSpline(a=a, b=b, x=x)$y
            wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
            tmp = tmp + y * wgt
          }
          d30.mult.status <- tmp
          d30.mult.status <- ifelse(data$hasFICOFlag == 1, d30.mult.status, noFICO)
        }
        d30.mdr.status[[q]] <- d30.mdr.status[[q]] * d30.mult.status
        if (test){
            mult = paste("d30", q, p, sep = "_")
            if (q == "reperf"){
                pickStatus = paste("pct", "rp", sep = "_") 
            }
            else if (q == "hampMod"){
                pickStatus = paste("pct", "hmod", sep = "_") 
            }
            else if (q == "nonHampMod"){
                pickStatus = paste("pct", "nhmod", sep = "_") 
            }
            else{
                pickStatus = paste("pct", "none", sep = "_") 
            }
            d30.mult.df[[mult]] = d30.mult.status * data[[pickStatus]] * 0.01 * pickD30
        }
      }
    }

    d30.mdr = d30.mdr * 0.01 * (d30.mdr.status$none*data$pct_none + d30.mdr.status$reperf*data$pct_rp + d30.mdr.status$hampMod*data$pct_hmod + d30.mdr.status$nonHampMod*data$pct_nhmod) * pickD30
    d30.mult.df$cumHpiIndexInterp                          <- NULL
    d30.mult.df$laggedUnemployChangeSinceStatusIndexInterp <- NULL
    if (!test){
        rm(d30.mult.df, d30.mult.status)    
    }
    
    end_time3 <- Sys.time()
    cat("d30 ", difftime(end_time3, start_time3, units = "mins"), "\n")


  } else {
    d30.mdr <- NA
  }

  if (! any(is.na(d60.spl)) ) {
    start_time4 <- Sys.time()

    cat("running d60 mdl", "\n")

    pickD60 = ifelse(data$delMonths == 2, 1, 0)
    d60.seasonals <- SeasonalAdjustment(seasonals = d60.spl$seasonalityMultipliers, months = data$monthBucket)
    d60.mdr <- rep(d60.spl$baselineConstant, times=nrow(data)) * d60.seasonals * d60.spl$adjustmentFactor
    param.d60 <- names(d60.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp"), names(d60.spl))]
    d60.mdr.status <- data.frame(matrix(1, nrow = nrow(data), ncol = 4))
    names(d60.mdr.status) <- param.d60
    d60.mult.df <- data.frame(matrix(1, nrow = nrow(data), ncol = 2))
    names(d60.mult.df) <- c("cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp")

    # get cumHpi index
    a <- unlist(d60.spl["cumHpiIndexInterp"][[1]][1])
    b <- unlist(d60.spl["cumHpiIndexInterp"][[1]][2])
    x <- data$fico
    d60.mult.df[, "cumHpiIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d60.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][1])
    b <- unlist(d60.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][2])
    x <- data$fico
    d60.mult.df[, "laggedUnemployChangeSinceStatusIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y

    for (q in param.d60) {
      d60.spl.status  <- d60.spl[[q]]
      d60.mult.status <- rep(1, times=nrow(data))

      if (q == 'none'){
        param.d60.status <- names(d60.spl.status)[-match(c("noFico", "noDti"),
                                                         names(d60.spl.status))]
      }
      else{
        param.d60.status <- names(d60.spl.status)
      }

      # add data frame for multiplier
      for (p in param.d60.status) {  
        #cat(q, p, "\n")
        idx <- match(p, names(d60.spl.status))
        # don't need to interpolate
        if (p != "cumHpi" & p != "laggedUnemployChangeSinceStatus"){
          a <- unlist(d60.spl.status[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
          b <- unlist(d60.spl.status[idx][[1]][2])
          x <- data[[p]]
          d60.mult.status <- BuildSpline(a=a, b=b, x=x)$y
          if (p == 'dti'){
            d60.mult.status <- ifelse(data$dti == -999, d60.spl.status$noDti, d60.mult.status)
          }
          if (p == "fico"){
            d60.mult.status <- ifelse(data$hasFICOFlag == 0, d60.spl.status$noFico, d60.mult.status)
          }
        }
        # need to interpolate
        else{
          interp = d60.spl.status[p][[1]]$interpAttribute
          n <- length(d60.spl.status[p][[1]]$functions)
          y <- rep(0, times = nrow(data))
          wgt <- rep(0, times = nrow(data))
          interpIdx = d60.mult.df[, interp]
          tmp = rep(0, times = nrow(data))

          a <- unlist(d60.spl.status[p][[1]]$functions[[1]][1])
          b <- unlist(d60.spl.status[p][[1]]$functions[[1]][2])
          x <- data[[p]]
          noFICO <- BuildSpline(a=a, b=b, x=x)$y

          for (i in 2: n){
            a <- unlist(d60.spl.status[p][[1]]$functions[[i]][1])
            b <- unlist(d60.spl.status[p][[1]]$functions[[i]][2])
            x <- data[[p]]
            y <- BuildSpline(a=a, b=b, x=x)$y
            wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
            tmp = tmp + y * wgt
          }
          d60.mult.status <- tmp
          d60.mult.status <- ifelse(data$hasFICOFlag == 1, d60.mult.status, noFICO)
        }
        d60.mdr.status[[q]] <- d60.mdr.status[[q]] * d60.mult.status        
        if (test){
            mult = paste("d60", q, p, sep = "_")
            if (q == "reperf"){
                pickStatus = paste("pct", "rp", sep = "_") 
            }
            else if (q == "hampMod"){
                pickStatus = paste("pct", "hmod", sep = "_") 
            }
            else if (q == "nonHampMod"){
                pickStatus = paste("pct", "nhmod", sep = "_") 
            }
            else{
                pickStatus = paste("pct", "none", sep = "_") 
            }
            d60.mult.df[[mult]] = d60.mult.status * data[[pickStatus]] * 0.01 * pickD60
        }
      }
    }       
    d60.mdr = d60.mdr * 0.01 * (d60.mdr.status$none*data$pct_none + d60.mdr.status$reperf*data$pct_rp + d60.mdr.status$hampMod*data$pct_hmod + d60.mdr.status$nonHampMod*data$pct_nhmod) * pickD60
    d60.mult.df$cumHpiIndexInterp                          <- NULL
    d60.mult.df$laggedUnemployChangeSinceStatusIndexInterp <- NULL    
    if (!test){
        rm(d60.mult.df, d60.mult.status)    
    }
    
    end_time4 <- Sys.time()
    cat("d60 ", difftime(end_time4, start_time4, units = "mins"), "\n")
  } else {
    d60.mdr <- NA
  }

  if (! any(is.na(d90.spl)) ) {
    start_time4 <- Sys.time()

    cat("running d90 mdl", "\n")

    pickD90 = ifelse(data$delMonths == 3, 1, 0)
    d90.seasonals <- SeasonalAdjustment(seasonals = d90.spl$seasonalityMultipliers, months = data$monthBucket)
    d90.mdr <- rep(d90.spl$baselineConstant, times=nrow(data)) * d90.seasonals * d90.spl$adjustmentFactor
    param.d90 <- names(d90.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp"), names(d90.spl))]
    d90.mdr.status <- data.frame(matrix(1, nrow = nrow(data), ncol = 4))
    names(d90.mdr.status) <- param.d90
    d90.mult.df <- data.frame(matrix(1, nrow = nrow(data), ncol = 2))
    names(d90.mult.df) <- c("cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp")

    # get cumHpi index
    a <- unlist(d90.spl["cumHpiIndexInterp"][[1]][1])
    b <- unlist(d90.spl["cumHpiIndexInterp"][[1]][2])
    x <- data$fico
    d90.mult.df[, "cumHpiIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d90.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][1])
    b <- unlist(d90.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][2])
    x <- data$fico
    d90.mult.df[, "laggedUnemployChangeSinceStatusIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y

    for (q in param.d90) {
      d90.spl.status  <- d90.spl[[q]]
      d90.mult.status <- rep(1, times=nrow(data))

      if (q == 'none'){
        param.d90.status <- names(d90.spl.status)[-match(c("noFico", "noDti", "monthsSince1", "monthsSince2"),
                                                         names(d90.spl.status))]
      }
      else{
        param.d90.status <- names(d90.spl.status)[-match(c("monthsSince1", "monthsSince2"),
                                                         names(d90.spl.status))]
      }

      # add data frame for multiplier
      for (p in param.d90.status) {
        idx <- match(p, names(d90.spl.status))
        # don't need to interpolate
        if (p != "cumHpi" & p != "laggedUnemployChangeSinceStatus"){
          a <- unlist(d90.spl.status[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
          b <- unlist(d90.spl.status[idx][[1]][2])
          x <- data[[p]]
          d90.mult.status <- BuildSpline(a=a, b=b, x=x)$y
          if (p == 'dti'){
            d90.mult.status <- ifelse(data$dti == -999, d90.spl.status$noDti, d90.mult.status)
          }
          if (p == "fico"){
            d90.mult.status <- ifelse(data$hasFICOFlag == 0, d90.spl.status$noFico, d90.mult.status)
          }
        }
        # need to interpolate
        else{
          interp = d90.spl.status[p][[1]]$interpAttribute
          n <- length(d90.spl.status[p][[1]]$functions)
          y <- rep(0, times = nrow(data))
          wgt <- rep(0, times = nrow(data))
          interpIdx = d90.mult.df[, interp]
          tmp = rep(0, times = nrow(data))

          a <- unlist(d90.spl.status[p][[1]]$functions[[1]][1])
          b <- unlist(d90.spl.status[p][[1]]$functions[[1]][2])
          x <- data[[p]]
          noFICO <- BuildSpline(a=a, b=b, x=x)$y

          for (i in 2: n){
            a <- unlist(d90.spl.status[p][[1]]$functions[[i]][1])
            b <- unlist(d90.spl.status[p][[1]]$functions[[i]][2])
            x <- data[[p]]
            y <- BuildSpline(a=a, b=b, x=x)$y
            wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
            tmp = tmp + y * wgt
          }
          d90.mult.status <- tmp
          d90.mult.status <- ifelse(data$hasFICOFlag == 1, d90.mult.status, noFICO)
        }
        d90.mdr.status[[q]] <- d90.mdr.status[[q]] * d90.mult.status
        if (test){
            mult = paste("d90", q, p, sep = "_")
            if (q == "reperf"){
                pickStatus = paste("pct", "rp", sep = "_") 
            }
            else if (q == "hampMod"){
                pickStatus = paste("pct", "hmod", sep = "_") 
            }
            else if (q == "nonHampMod"){
                pickStatus = paste("pct", "nhmod", sep = "_") 
            }
            else{
                pickStatus = paste("pct", "none", sep = "_") 
            }
            d90.mult.df[[mult]] = d90.mult.status * data[[pickStatus]] * 0.01 * pickD90
        }        
      }
    }

    d90.mdr = d90.mdr * 0.01 * (d90.mdr.status$none*data$pct_none + d90.mdr.status$reperf*data$pct_rp + d90.mdr.status$hampMod*data$pct_hmod + d90.mdr.status$nonHampMod*data$pct_nhmod) * pickD90
    d90.mult.df$cumHpiIndexInterp                          <- NULL
    d90.mult.df$laggedUnemployChangeSinceStatusIndexInterp <- NULL    
    if (!test){
        rm(d90.mult.df, d90.mult.status)
    }

    end_time5 <- Sys.time()
    cat("d90 ", difftime(end_time5, start_time5, units = "mins"), "\n")
  } else {
    d90.mdr <- NA
  }

  if (! any(is.na(cure.spl)) ) {
    cat("running cure mdl\n")

    pickD90 = ifelse(data$delMonths == 3, 1, 0)
    param.cure <- names(cure.spl)[-match(c("baselineConstant", "adjustmentFactor"),
                                         names(cure.spl))]
    cure.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.cure)))
    names(cure.mult.df) <- param.cure
    cure.mdr <- rep(cure.spl$baselineConstant, times=nrow(data))
    stay.mdr <- rep(cure.spl$baselineConstant, times=nrow(data))

    for (p in param.cure) {

      idx <- match(p, names(cure.spl))
      a <- unlist(cure.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
      b <- unlist(cure.spl[idx][[1]][2])
      x <- data[[p]]
      cure.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
      cure.mdr <- cure.mdr * cure.mult.df[, p]
    }
    stay.mdr <- 1 - cure.mdr

    cure.mdr = cure.mdr * pickD90
    stay.mdr = stay.mdr * pickD90
    cure.mult.df = cure.mult.df * pickD90

    names(cure.mult.df) <- paste(paste("CURE", names(cure.mult.df), sep="_"), version, sep="_")

  } else {
    cure.mdr <- NA
  }

  if (! any(is.na(buyout.spl)) ) {
    start_time6 <- Sys.time()

    cat("running buyout mdl\n")

    buyout.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=4))
    names(buyout.mult.df) <- c("servicerBuyoutIndex", "buyoutIncentiveShift", "BuyoutLowMult", "BuyoutHighMult")
    buyout.mdr <- rep(1, length(data))
    buyout.submdl <- buyout.spl$buyoutIncentive$functions

    # Get index interp
    aServicer <- unlist(buyout.spl["servicerBuyoutIndexInterp"][[1]][1])
    bServicer <- unlist(buyout.spl["servicerBuyoutIndexInterp"][[1]][2])
    xServicer <- data[["servicerBuyoutIndex"]]
    buyout.mult.df[, "servicerBuyoutIndex"] <- BuildSpline(a=aServicer, b=bServicer, x=xServicer)$y

    # Elbow shift
    aElbow <- unlist(buyout.spl["servicerBuyoutIndexElbow"][[1]][1])
    bElbow <- unlist(buyout.spl["servicerBuyoutIndexElbow"][[1]][2])
    buyout.mult.df[, "buyoutIncentiveShift"] <- BuildSpline(a=aElbow, b=bElbow, x=xServicer)$y

    #Buyout Incentive
    x <- data[["buyoutIncentive"]] + buyout.mult.df[["buyoutIncentiveShift"]]

    # Buyout 0 curve
    aLow <- unlist(buyout.submdl[[1]][1])
    bLow <- unlist(buyout.submdl[[1]][2])
    buyout.mult.df[, "BuyoutLowMult"] <- BuildSpline(a=aLow, b=bLow, x=x)$y

    #Buyout 100 curve
    aHigh <- unlist(buyout.submdl[[2]][1])
    bHigh <- unlist(buyout.submdl[[2]][2])
    buyout.mult.df[, "BuyoutHighMult"] <- BuildSpline(a=aHigh, b=bHigh, x=x)$y

    buyout.mdr <- buyout.mult.df[["BuyoutLowMult"]] * (1 - buyout.mult.df[["servicerBuyoutIndex"]]) + buyout.mult.df[["BuyoutHighMult"]] * buyout.mult.df[["servicerBuyoutIndex"]]

    end_time6 <- Sys.time()
    cat("buyout ", difftime(end_time6, start_time6, units = "mins"), "\n")

  } else {
    buyout.mdr <- NA
  }

  if ( any(is.na(d0.spl)) | any(is.na(d30.spl)) | any(is.na(d60.spl)) | any(is.na(cure.spl)) | any(is.na(buyout.spl)) ) {
    all.mdr <- NA
    return(list("pred"=cure.mdr, "mult"=cure.mult.df))
  } else {
    #result.mdr <- (d0.mdr + d30.mdr + d60.mdr + stay.mdr) * buyout.mdr
    #transit.mdr <- d0.mdr + d30.mdr + d60.mdr + stay.mdr*d90.mdr    
    result.mdr <- (d0.mdr + d30.mdr + d60.mdr + stay.mdr) * buyout.mdr
    transit.mdr <- d0.mdr + d30.mdr + d60.mdr + stay.mdr    
    if (test){
        mult.df <- data.frame(cbind(d0.mult.df, d30.mult.df, d60.mult.df, d0.mdr, d30.mdr, d60.mdr, buyout.mult.df, transit.mdr, buyout.mdr, result.mdr))
        #print(mult.df)
        #return(list("pred_all"=all.mdr, "pred_d0"=d0.mdr, "pred_d30"=d30.mdr, "pred_d60"=d60.mdr, "pred_stay"=stay.mdr,
        #            "pred_transition"=transit.mdr, "pred_buyout"=buyout.mdr, mult.df))   
        return (mult.df)
    }
    else{
        return(list("pred_all"=result.mdr, "pred_transition"=transit.mdr, "pred_buyout"=buyout.mdr))    
    }
  }


}
