// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrentCoupon.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CurrentCoupon.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ccm {
namespace quantlib {
namespace input {

namespace {

const ::google::protobuf::Descriptor* CurrentCoupon_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CurrentCoupon_reflection_ = NULL;
const ::google::protobuf::Descriptor* CurrentCoupon_TBA_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CurrentCoupon_TBA_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CurrentCoupon_2eproto() {
  protobuf_AddDesc_CurrentCoupon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CurrentCoupon.proto");
  GOOGLE_CHECK(file != NULL);
  CurrentCoupon_descriptor_ = file->message_type(0);
  static const int CurrentCoupon_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon, close_date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon, tba_),
  };
  CurrentCoupon_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CurrentCoupon_descriptor_,
      CurrentCoupon::default_instance_,
      CurrentCoupon_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CurrentCoupon));
  CurrentCoupon_TBA_descriptor_ = CurrentCoupon_descriptor_->nested_type(0);
  static const int CurrentCoupon_TBA_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon_TBA, ticker_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon_TBA, price_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon_TBA, settle_date_),
  };
  CurrentCoupon_TBA_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CurrentCoupon_TBA_descriptor_,
      CurrentCoupon_TBA::default_instance_,
      CurrentCoupon_TBA_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon_TBA, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCoupon_TBA, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CurrentCoupon_TBA));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CurrentCoupon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CurrentCoupon_descriptor_, &CurrentCoupon::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CurrentCoupon_TBA_descriptor_, &CurrentCoupon_TBA::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CurrentCoupon_2eproto() {
  delete CurrentCoupon::default_instance_;
  delete CurrentCoupon_reflection_;
  delete CurrentCoupon_TBA::default_instance_;
  delete CurrentCoupon_TBA_reflection_;
}

void protobuf_AddDesc_CurrentCoupon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023CurrentCoupon.proto\022\022ccm.quantlib.inpu"
    "t\"\227\001\n\rCurrentCoupon\022\022\n\nclose_date\030\001 \002(\003\022"
    "2\n\003tba\030d \003(\0132%.ccm.quantlib.input.Curren"
    "tCoupon.TBA\032>\n\003TBA\022\023\n\013ticker_name\030\001 \002(\t\022"
    "\r\n\005price\030\002 \002(\001\022\023\n\013settle_date\030\003 \002(\003B\002H\001", 199);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CurrentCoupon.proto", &protobuf_RegisterTypes);
  CurrentCoupon::default_instance_ = new CurrentCoupon();
  CurrentCoupon_TBA::default_instance_ = new CurrentCoupon_TBA();
  CurrentCoupon::default_instance_->InitAsDefaultInstance();
  CurrentCoupon_TBA::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CurrentCoupon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CurrentCoupon_2eproto {
  StaticDescriptorInitializer_CurrentCoupon_2eproto() {
    protobuf_AddDesc_CurrentCoupon_2eproto();
  }
} static_descriptor_initializer_CurrentCoupon_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CurrentCoupon_TBA::kTickerNameFieldNumber;
const int CurrentCoupon_TBA::kPriceFieldNumber;
const int CurrentCoupon_TBA::kSettleDateFieldNumber;
#endif  // !_MSC_VER

CurrentCoupon_TBA::CurrentCoupon_TBA()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CurrentCoupon_TBA::InitAsDefaultInstance() {
}

CurrentCoupon_TBA::CurrentCoupon_TBA(const CurrentCoupon_TBA& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CurrentCoupon_TBA::SharedCtor() {
  _cached_size_ = 0;
  ticker_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  price_ = 0;
  settle_date_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CurrentCoupon_TBA::~CurrentCoupon_TBA() {
  SharedDtor();
}

void CurrentCoupon_TBA::SharedDtor() {
  if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
    delete ticker_name_;
  }
  if (this != default_instance_) {
  }
}

void CurrentCoupon_TBA::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CurrentCoupon_TBA::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CurrentCoupon_TBA_descriptor_;
}

const CurrentCoupon_TBA& CurrentCoupon_TBA::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CurrentCoupon_2eproto();
  return *default_instance_;
}

CurrentCoupon_TBA* CurrentCoupon_TBA::default_instance_ = NULL;

CurrentCoupon_TBA* CurrentCoupon_TBA::New() const {
  return new CurrentCoupon_TBA;
}

void CurrentCoupon_TBA::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_ticker_name()) {
      if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
        ticker_name_->clear();
      }
    }
    price_ = 0;
    settle_date_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CurrentCoupon_TBA::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string ticker_name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ticker_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->ticker_name().data(), this->ticker_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_price;
        break;
      }

      // required double price = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_price:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &price_)));
          set_has_price();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_settle_date;
        break;
      }

      // required int64 settle_date = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_settle_date:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &settle_date_)));
          set_has_settle_date();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CurrentCoupon_TBA::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string ticker_name = 1;
  if (has_ticker_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ticker_name().data(), this->ticker_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->ticker_name(), output);
  }

  // required double price = 2;
  if (has_price()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->price(), output);
  }

  // required int64 settle_date = 3;
  if (has_settle_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->settle_date(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CurrentCoupon_TBA::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string ticker_name = 1;
  if (has_ticker_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ticker_name().data(), this->ticker_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ticker_name(), target);
  }

  // required double price = 2;
  if (has_price()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->price(), target);
  }

  // required int64 settle_date = 3;
  if (has_settle_date()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->settle_date(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CurrentCoupon_TBA::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string ticker_name = 1;
    if (has_ticker_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ticker_name());
    }

    // required double price = 2;
    if (has_price()) {
      total_size += 1 + 8;
    }

    // required int64 settle_date = 3;
    if (has_settle_date()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->settle_date());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CurrentCoupon_TBA::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CurrentCoupon_TBA* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CurrentCoupon_TBA*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CurrentCoupon_TBA::MergeFrom(const CurrentCoupon_TBA& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ticker_name()) {
      set_ticker_name(from.ticker_name());
    }
    if (from.has_price()) {
      set_price(from.price());
    }
    if (from.has_settle_date()) {
      set_settle_date(from.settle_date());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CurrentCoupon_TBA::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CurrentCoupon_TBA::CopyFrom(const CurrentCoupon_TBA& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CurrentCoupon_TBA::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void CurrentCoupon_TBA::Swap(CurrentCoupon_TBA* other) {
  if (other != this) {
    std::swap(ticker_name_, other->ticker_name_);
    std::swap(price_, other->price_);
    std::swap(settle_date_, other->settle_date_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CurrentCoupon_TBA::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CurrentCoupon_TBA_descriptor_;
  metadata.reflection = CurrentCoupon_TBA_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int CurrentCoupon::kCloseDateFieldNumber;
const int CurrentCoupon::kTbaFieldNumber;
#endif  // !_MSC_VER

CurrentCoupon::CurrentCoupon()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CurrentCoupon::InitAsDefaultInstance() {
}

CurrentCoupon::CurrentCoupon(const CurrentCoupon& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CurrentCoupon::SharedCtor() {
  _cached_size_ = 0;
  close_date_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CurrentCoupon::~CurrentCoupon() {
  SharedDtor();
}

void CurrentCoupon::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CurrentCoupon::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CurrentCoupon::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CurrentCoupon_descriptor_;
}

const CurrentCoupon& CurrentCoupon::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CurrentCoupon_2eproto();
  return *default_instance_;
}

CurrentCoupon* CurrentCoupon::default_instance_ = NULL;

CurrentCoupon* CurrentCoupon::New() const {
  return new CurrentCoupon;
}

void CurrentCoupon::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    close_date_ = GOOGLE_LONGLONG(0);
  }
  tba_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CurrentCoupon::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 close_date = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &close_date_)));
          set_has_close_date();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(802)) goto parse_tba;
        break;
      }

      // repeated .ccm.quantlib.input.CurrentCoupon.TBA tba = 100;
      case 100: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_tba:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_tba()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(802)) goto parse_tba;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CurrentCoupon::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 close_date = 1;
  if (has_close_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->close_date(), output);
  }

  // repeated .ccm.quantlib.input.CurrentCoupon.TBA tba = 100;
  for (int i = 0; i < this->tba_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      100, this->tba(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CurrentCoupon::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 close_date = 1;
  if (has_close_date()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->close_date(), target);
  }

  // repeated .ccm.quantlib.input.CurrentCoupon.TBA tba = 100;
  for (int i = 0; i < this->tba_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        100, this->tba(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CurrentCoupon::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 close_date = 1;
    if (has_close_date()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->close_date());
    }

  }
  // repeated .ccm.quantlib.input.CurrentCoupon.TBA tba = 100;
  total_size += 2 * this->tba_size();
  for (int i = 0; i < this->tba_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tba(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CurrentCoupon::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CurrentCoupon* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CurrentCoupon*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CurrentCoupon::MergeFrom(const CurrentCoupon& from) {
  GOOGLE_CHECK_NE(&from, this);
  tba_.MergeFrom(from.tba_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_close_date()) {
      set_close_date(from.close_date());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CurrentCoupon::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CurrentCoupon::CopyFrom(const CurrentCoupon& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CurrentCoupon::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < tba_size(); i++) {
    if (!this->tba(i).IsInitialized()) return false;
  }
  return true;
}

void CurrentCoupon::Swap(CurrentCoupon* other) {
  if (other != this) {
    std::swap(close_date_, other->close_date_);
    tba_.Swap(&other->tba_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CurrentCoupon::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CurrentCoupon_descriptor_;
  metadata.reflection = CurrentCoupon_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace input
}  // namespace quantlib
}  // namespace ccm

// @@protoc_insertion_point(global_scope)
