// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace ccm.quantlib.input {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class CurrentCoupon {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_ccm_quantlib_input_CurrentCoupon__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::ccm.quantlib.input.CurrentCoupon, global::ccm.quantlib.input.CurrentCoupon.Builder> internal__static_ccm_quantlib_input_CurrentCoupon__FieldAccessorTable;
      internal static pbd::MessageDescriptor internal__static_ccm_quantlib_input_CurrentCoupon_TBA__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::ccm.quantlib.input.CurrentCoupon.Types.TBA, global::ccm.quantlib.input.CurrentCoupon.Types.TBA.Builder> internal__static_ccm_quantlib_input_CurrentCoupon_TBA__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static CurrentCoupon() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "ChNDdXJyZW50Q291cG9uLnByb3RvEhJjY20ucXVhbnRsaWIuaW5wdXQilwEK" + 
            "DUN1cnJlbnRDb3Vwb24SEgoKY2xvc2VfZGF0ZRgBIAIoAxIyCgN0YmEYZCAD" + 
            "KAsyJS5jY20ucXVhbnRsaWIuaW5wdXQuQ3VycmVudENvdXBvbi5UQkEaPgoD" + 
            "VEJBEhMKC3RpY2tlcl9uYW1lGAEgAigJEg0KBXByaWNlGAIgAigBEhMKC3Nl" + 
            "dHRsZV9kYXRlGAMgAigDQgJIAQ==");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_ccm_quantlib_input_CurrentCoupon__Descriptor = Descriptor.MessageTypes[0];
          internal__static_ccm_quantlib_input_CurrentCoupon__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::ccm.quantlib.input.CurrentCoupon, global::ccm.quantlib.input.CurrentCoupon.Builder>(internal__static_ccm_quantlib_input_CurrentCoupon__Descriptor,
                  new string[] { "CloseDate", "Tba", });
          internal__static_ccm_quantlib_input_CurrentCoupon_TBA__Descriptor = internal__static_ccm_quantlib_input_CurrentCoupon__Descriptor.NestedTypes[0];
          internal__static_ccm_quantlib_input_CurrentCoupon_TBA__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::ccm.quantlib.input.CurrentCoupon.Types.TBA, global::ccm.quantlib.input.CurrentCoupon.Types.TBA.Builder>(internal__static_ccm_quantlib_input_CurrentCoupon_TBA__Descriptor,
                  new string[] { "TickerName", "Price", "SettleDate", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CurrentCoupon : pb::GeneratedMessage<CurrentCoupon, CurrentCoupon.Builder> {
    private CurrentCoupon() { }
    private static readonly CurrentCoupon defaultInstance = new CurrentCoupon().MakeReadOnly();
    private static readonly string[] _currentCouponFieldNames = new string[] { "close_date", "tba" };
    private static readonly uint[] _currentCouponFieldTags = new uint[] { 8, 802 };
    public static CurrentCoupon DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override CurrentCoupon DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override CurrentCoupon ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::ccm.quantlib.input.Proto.CurrentCoupon.internal__static_ccm_quantlib_input_CurrentCoupon__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<CurrentCoupon, CurrentCoupon.Builder> InternalFieldAccessors {
      get { return global::ccm.quantlib.input.Proto.CurrentCoupon.internal__static_ccm_quantlib_input_CurrentCoupon__FieldAccessorTable; }
    }
    
    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class TBA : pb::GeneratedMessage<TBA, TBA.Builder> {
        private TBA() { }
        private static readonly TBA defaultInstance = new TBA().MakeReadOnly();
        private static readonly string[] _tBAFieldNames = new string[] { "price", "settle_date", "ticker_name" };
        private static readonly uint[] _tBAFieldTags = new uint[] { 17, 24, 10 };
        public static TBA DefaultInstance {
          get { return defaultInstance; }
        }
        
        public override TBA DefaultInstanceForType {
          get { return DefaultInstance; }
        }
        
        protected override TBA ThisMessage {
          get { return this; }
        }
        
        public static pbd::MessageDescriptor Descriptor {
          get { return global::ccm.quantlib.input.Proto.CurrentCoupon.internal__static_ccm_quantlib_input_CurrentCoupon_TBA__Descriptor; }
        }
        
        protected override pb::FieldAccess.FieldAccessorTable<TBA, TBA.Builder> InternalFieldAccessors {
          get { return global::ccm.quantlib.input.Proto.CurrentCoupon.internal__static_ccm_quantlib_input_CurrentCoupon_TBA__FieldAccessorTable; }
        }
        
        public const int TickerNameFieldNumber = 1;
        private bool hasTickerName;
        private string tickerName_ = "";
        public bool HasTickerName {
          get { return hasTickerName; }
        }
        public string TickerName {
          get { return tickerName_; }
        }
        
        public const int PriceFieldNumber = 2;
        private bool hasPrice;
        private double price_;
        public bool HasPrice {
          get { return hasPrice; }
        }
        public double Price {
          get { return price_; }
        }
        
        public const int SettleDateFieldNumber = 3;
        private bool hasSettleDate;
        private long settleDate_;
        public bool HasSettleDate {
          get { return hasSettleDate; }
        }
        public long SettleDate {
          get { return settleDate_; }
        }
        
        public override bool IsInitialized {
          get {
            if (!hasTickerName) return false;
            if (!hasPrice) return false;
            if (!hasSettleDate) return false;
            return true;
          }
        }
        
        public override void WriteTo(pb::ICodedOutputStream output) {
          int size = SerializedSize;
          string[] field_names = _tBAFieldNames;
          if (hasTickerName) {
            output.WriteString(1, field_names[2], TickerName);
          }
          if (hasPrice) {
            output.WriteDouble(2, field_names[0], Price);
          }
          if (hasSettleDate) {
            output.WriteInt64(3, field_names[1], SettleDate);
          }
          UnknownFields.WriteTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        public override int SerializedSize {
          get {
            int size = memoizedSerializedSize;
            if (size != -1) return size;
            
            size = 0;
            if (hasTickerName) {
              size += pb::CodedOutputStream.ComputeStringSize(1, TickerName);
            }
            if (hasPrice) {
              size += pb::CodedOutputStream.ComputeDoubleSize(2, Price);
            }
            if (hasSettleDate) {
              size += pb::CodedOutputStream.ComputeInt64Size(3, SettleDate);
            }
            size += UnknownFields.SerializedSize;
            memoizedSerializedSize = size;
            return size;
          }
        }
        
        public static TBA ParseFrom(pb::ByteString data) {
          return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        }
        public static TBA ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
          return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        }
        public static TBA ParseFrom(byte[] data) {
          return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
        }
        public static TBA ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
          return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
        }
        public static TBA ParseFrom(global::System.IO.Stream input) {
          return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        }
        public static TBA ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
          return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        }
        public static TBA ParseDelimitedFrom(global::System.IO.Stream input) {
          return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
        }
        public static TBA ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
          return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
        }
        public static TBA ParseFrom(pb::ICodedInputStream input) {
          return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
        }
        public static TBA ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
        }
        private TBA MakeReadOnly() {
          return this;
        }
        
        public static Builder CreateBuilder() { return new Builder(); }
        public override Builder ToBuilder() { return CreateBuilder(this); }
        public override Builder CreateBuilderForType() { return new Builder(); }
        public static Builder CreateBuilder(TBA prototype) {
          return new Builder(prototype);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed partial class Builder : pb::GeneratedBuilder<TBA, Builder> {
          protected override Builder ThisBuilder {
            get { return this; }
          }
          public Builder() {
            result = DefaultInstance;
            resultIsReadOnly = true;
          }
          internal Builder(TBA cloneFrom) {
            result = cloneFrom;
            resultIsReadOnly = true;
          }
          
          private bool resultIsReadOnly;
          private TBA result;
          
          private TBA PrepareBuilder() {
            if (resultIsReadOnly) {
              TBA original = result;
              result = new TBA();
              resultIsReadOnly = false;
              MergeFrom(original);
            }
            return result;
          }
          
          public override bool IsInitialized {
            get { return result.IsInitialized; }
          }
          
          protected override TBA MessageBeingBuilt {
            get { return PrepareBuilder(); }
          }
          
          public override Builder Clear() {
            result = DefaultInstance;
            resultIsReadOnly = true;
            return this;
          }
          
          public override Builder Clone() {
            if (resultIsReadOnly) {
              return new Builder(result);
            } else {
              return new Builder().MergeFrom(result);
            }
          }
          
          public override pbd::MessageDescriptor DescriptorForType {
            get { return global::ccm.quantlib.input.CurrentCoupon.Types.TBA.Descriptor; }
          }
          
          public override TBA DefaultInstanceForType {
            get { return global::ccm.quantlib.input.CurrentCoupon.Types.TBA.DefaultInstance; }
          }
          
          public override TBA BuildPartial() {
            if (resultIsReadOnly) {
              return result;
            }
            resultIsReadOnly = true;
            return result.MakeReadOnly();
          }
          
          public override Builder MergeFrom(pb::IMessage other) {
            if (other is TBA) {
              return MergeFrom((TBA) other);
            } else {
              base.MergeFrom(other);
              return this;
            }
          }
          
          public override Builder MergeFrom(TBA other) {
            if (other == global::ccm.quantlib.input.CurrentCoupon.Types.TBA.DefaultInstance) return this;
            PrepareBuilder();
            if (other.HasTickerName) {
              TickerName = other.TickerName;
            }
            if (other.HasPrice) {
              Price = other.Price;
            }
            if (other.HasSettleDate) {
              SettleDate = other.SettleDate;
            }
            this.MergeUnknownFields(other.UnknownFields);
            return this;
          }
          
          public override Builder MergeFrom(pb::ICodedInputStream input) {
            return MergeFrom(input, pb::ExtensionRegistry.Empty);
          }
          
          public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
            PrepareBuilder();
            pb::UnknownFieldSet.Builder unknownFields = null;
            uint tag;
            string field_name;
            while (input.ReadTag(out tag, out field_name)) {
              if(tag == 0 && field_name != null) {
                int field_ordinal = global::System.Array.BinarySearch(_tBAFieldNames, field_name, global::System.StringComparer.Ordinal);
                if(field_ordinal >= 0)
                  tag = _tBAFieldTags[field_ordinal];
                else {
                  if (unknownFields == null) {
                    unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                  }
                  ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                  continue;
                }
              }
              switch (tag) {
                case 0: {
                  throw pb::InvalidProtocolBufferException.InvalidTag();
                }
                default: {
                  if (pb::WireFormat.IsEndGroupTag(tag)) {
                    if (unknownFields != null) {
                      this.UnknownFields = unknownFields.Build();
                    }
                    return this;
                  }
                  if (unknownFields == null) {
                    unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                  }
                  ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                  break;
                }
                case 10: {
                  result.hasTickerName = input.ReadString(ref result.tickerName_);
                  break;
                }
                case 17: {
                  result.hasPrice = input.ReadDouble(ref result.price_);
                  break;
                }
                case 24: {
                  result.hasSettleDate = input.ReadInt64(ref result.settleDate_);
                  break;
                }
              }
            }
            
            if (unknownFields != null) {
              this.UnknownFields = unknownFields.Build();
            }
            return this;
          }
          
          
          public bool HasTickerName {
            get { return result.hasTickerName; }
          }
          public string TickerName {
            get { return result.TickerName; }
            set { SetTickerName(value); }
          }
          public Builder SetTickerName(string value) {
            pb::ThrowHelper.ThrowIfNull(value, "value");
            PrepareBuilder();
            result.hasTickerName = true;
            result.tickerName_ = value;
            return this;
          }
          public Builder ClearTickerName() {
            PrepareBuilder();
            result.hasTickerName = false;
            result.tickerName_ = "";
            return this;
          }
          
          public bool HasPrice {
            get { return result.hasPrice; }
          }
          public double Price {
            get { return result.Price; }
            set { SetPrice(value); }
          }
          public Builder SetPrice(double value) {
            PrepareBuilder();
            result.hasPrice = true;
            result.price_ = value;
            return this;
          }
          public Builder ClearPrice() {
            PrepareBuilder();
            result.hasPrice = false;
            result.price_ = 0D;
            return this;
          }
          
          public bool HasSettleDate {
            get { return result.hasSettleDate; }
          }
          public long SettleDate {
            get { return result.SettleDate; }
            set { SetSettleDate(value); }
          }
          public Builder SetSettleDate(long value) {
            PrepareBuilder();
            result.hasSettleDate = true;
            result.settleDate_ = value;
            return this;
          }
          public Builder ClearSettleDate() {
            PrepareBuilder();
            result.hasSettleDate = false;
            result.settleDate_ = 0L;
            return this;
          }
        }
        static TBA() {
          object.ReferenceEquals(global::ccm.quantlib.input.Proto.CurrentCoupon.Descriptor, null);
        }
      }
      
    }
    #endregion
    
    public const int CloseDateFieldNumber = 1;
    private bool hasCloseDate;
    private long closeDate_;
    public bool HasCloseDate {
      get { return hasCloseDate; }
    }
    public long CloseDate {
      get { return closeDate_; }
    }
    
    public const int TbaFieldNumber = 100;
    private pbc::PopsicleList<global::ccm.quantlib.input.CurrentCoupon.Types.TBA> tba_ = new pbc::PopsicleList<global::ccm.quantlib.input.CurrentCoupon.Types.TBA>();
    public scg::IList<global::ccm.quantlib.input.CurrentCoupon.Types.TBA> TbaList {
      get { return tba_; }
    }
    public int TbaCount {
      get { return tba_.Count; }
    }
    public global::ccm.quantlib.input.CurrentCoupon.Types.TBA GetTba(int index) {
      return tba_[index];
    }
    
    public override bool IsInitialized {
      get {
        if (!hasCloseDate) return false;
        foreach (global::ccm.quantlib.input.CurrentCoupon.Types.TBA element in TbaList) {
          if (!element.IsInitialized) return false;
        }
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _currentCouponFieldNames;
      if (hasCloseDate) {
        output.WriteInt64(1, field_names[0], CloseDate);
      }
      if (tba_.Count > 0) {
        output.WriteMessageArray(100, field_names[1], tba_);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasCloseDate) {
          size += pb::CodedOutputStream.ComputeInt64Size(1, CloseDate);
        }
        foreach (global::ccm.quantlib.input.CurrentCoupon.Types.TBA element in TbaList) {
          size += pb::CodedOutputStream.ComputeMessageSize(100, element);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static CurrentCoupon ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static CurrentCoupon ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static CurrentCoupon ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static CurrentCoupon ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static CurrentCoupon ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static CurrentCoupon ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static CurrentCoupon ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static CurrentCoupon ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static CurrentCoupon ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static CurrentCoupon ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private CurrentCoupon MakeReadOnly() {
      tba_.MakeReadOnly();
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(CurrentCoupon prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<CurrentCoupon, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(CurrentCoupon cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private CurrentCoupon result;
      
      private CurrentCoupon PrepareBuilder() {
        if (resultIsReadOnly) {
          CurrentCoupon original = result;
          result = new CurrentCoupon();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override CurrentCoupon MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::ccm.quantlib.input.CurrentCoupon.Descriptor; }
      }
      
      public override CurrentCoupon DefaultInstanceForType {
        get { return global::ccm.quantlib.input.CurrentCoupon.DefaultInstance; }
      }
      
      public override CurrentCoupon BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is CurrentCoupon) {
          return MergeFrom((CurrentCoupon) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(CurrentCoupon other) {
        if (other == global::ccm.quantlib.input.CurrentCoupon.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasCloseDate) {
          CloseDate = other.CloseDate;
        }
        if (other.tba_.Count != 0) {
          result.tba_.Add(other.tba_);
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_currentCouponFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _currentCouponFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasCloseDate = input.ReadInt64(ref result.closeDate_);
              break;
            }
            case 802: {
              input.ReadMessageArray(tag, field_name, result.tba_, global::ccm.quantlib.input.CurrentCoupon.Types.TBA.DefaultInstance, extensionRegistry);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasCloseDate {
        get { return result.hasCloseDate; }
      }
      public long CloseDate {
        get { return result.CloseDate; }
        set { SetCloseDate(value); }
      }
      public Builder SetCloseDate(long value) {
        PrepareBuilder();
        result.hasCloseDate = true;
        result.closeDate_ = value;
        return this;
      }
      public Builder ClearCloseDate() {
        PrepareBuilder();
        result.hasCloseDate = false;
        result.closeDate_ = 0L;
        return this;
      }
      
      public pbc::IPopsicleList<global::ccm.quantlib.input.CurrentCoupon.Types.TBA> TbaList {
        get { return PrepareBuilder().tba_; }
      }
      public int TbaCount {
        get { return result.TbaCount; }
      }
      public global::ccm.quantlib.input.CurrentCoupon.Types.TBA GetTba(int index) {
        return result.GetTba(index);
      }
      public Builder SetTba(int index, global::ccm.quantlib.input.CurrentCoupon.Types.TBA value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.tba_[index] = value;
        return this;
      }
      public Builder SetTba(int index, global::ccm.quantlib.input.CurrentCoupon.Types.TBA.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.tba_[index] = builderForValue.Build();
        return this;
      }
      public Builder AddTba(global::ccm.quantlib.input.CurrentCoupon.Types.TBA value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.tba_.Add(value);
        return this;
      }
      public Builder AddTba(global::ccm.quantlib.input.CurrentCoupon.Types.TBA.Builder builderForValue) {
        pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
        PrepareBuilder();
        result.tba_.Add(builderForValue.Build());
        return this;
      }
      public Builder AddRangeTba(scg::IEnumerable<global::ccm.quantlib.input.CurrentCoupon.Types.TBA> values) {
        PrepareBuilder();
        result.tba_.Add(values);
        return this;
      }
      public Builder ClearTba() {
        PrepareBuilder();
        result.tba_.Clear();
        return this;
      }
    }
    static CurrentCoupon() {
      object.ReferenceEquals(global::ccm.quantlib.input.Proto.CurrentCoupon.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
