// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace ccm.quantlib.input {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class CurrentCouponResult {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      internal static pbd::MessageDescriptor internal__static_ccm_quantlib_input_CurrentCouponResult__Descriptor;
      internal static pb::FieldAccess.FieldAccessorTable<global::ccm.quantlib.input.CurrentCouponResult, global::ccm.quantlib.input.CurrentCouponResult.Builder> internal__static_ccm_quantlib_input_CurrentCouponResult__FieldAccessorTable;
      #endregion
      #region Descriptor
      public static pbd::FileDescriptor Descriptor {
        get { return descriptor; }
      }
      private static pbd::FileDescriptor descriptor;
      
      static CurrentCouponResult() {
        byte[] descriptorData = global::System.Convert.FromBase64String(
            "ChlDdXJyZW50Q291cG9uUmVzdWx0LnByb3RvEhJjY20ucXVhbnRsaWIuaW5w" + 
            "dXQiTQoTQ3VycmVudENvdXBvblJlc3VsdBISCgpjbG9zZV9kYXRlGAEgAigD" + 
            "EhMKC3RpY2tlcl9uYW1lGAIgAigJEg0KBXByaWNlGAMgAigBQgJIAQ==");
        pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
          descriptor = root;
          internal__static_ccm_quantlib_input_CurrentCouponResult__Descriptor = Descriptor.MessageTypes[0];
          internal__static_ccm_quantlib_input_CurrentCouponResult__FieldAccessorTable = 
              new pb::FieldAccess.FieldAccessorTable<global::ccm.quantlib.input.CurrentCouponResult, global::ccm.quantlib.input.CurrentCouponResult.Builder>(internal__static_ccm_quantlib_input_CurrentCouponResult__Descriptor,
                  new string[] { "CloseDate", "TickerName", "Price", });
          return null;
        };
        pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
            new pbd::FileDescriptor[] {
            }, assigner);
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CurrentCouponResult : pb::GeneratedMessage<CurrentCouponResult, CurrentCouponResult.Builder> {
    private CurrentCouponResult() { }
    private static readonly CurrentCouponResult defaultInstance = new CurrentCouponResult().MakeReadOnly();
    private static readonly string[] _currentCouponResultFieldNames = new string[] { "close_date", "price", "ticker_name" };
    private static readonly uint[] _currentCouponResultFieldTags = new uint[] { 8, 25, 18 };
    public static CurrentCouponResult DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override CurrentCouponResult DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override CurrentCouponResult ThisMessage {
      get { return this; }
    }
    
    public static pbd::MessageDescriptor Descriptor {
      get { return global::ccm.quantlib.input.Proto.CurrentCouponResult.internal__static_ccm_quantlib_input_CurrentCouponResult__Descriptor; }
    }
    
    protected override pb::FieldAccess.FieldAccessorTable<CurrentCouponResult, CurrentCouponResult.Builder> InternalFieldAccessors {
      get { return global::ccm.quantlib.input.Proto.CurrentCouponResult.internal__static_ccm_quantlib_input_CurrentCouponResult__FieldAccessorTable; }
    }
    
    public const int CloseDateFieldNumber = 1;
    private bool hasCloseDate;
    private long closeDate_;
    public bool HasCloseDate {
      get { return hasCloseDate; }
    }
    public long CloseDate {
      get { return closeDate_; }
    }
    
    public const int TickerNameFieldNumber = 2;
    private bool hasTickerName;
    private string tickerName_ = "";
    public bool HasTickerName {
      get { return hasTickerName; }
    }
    public string TickerName {
      get { return tickerName_; }
    }
    
    public const int PriceFieldNumber = 3;
    private bool hasPrice;
    private double price_;
    public bool HasPrice {
      get { return hasPrice; }
    }
    public double Price {
      get { return price_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasCloseDate) return false;
        if (!hasTickerName) return false;
        if (!hasPrice) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _currentCouponResultFieldNames;
      if (hasCloseDate) {
        output.WriteInt64(1, field_names[0], CloseDate);
      }
      if (hasTickerName) {
        output.WriteString(2, field_names[2], TickerName);
      }
      if (hasPrice) {
        output.WriteDouble(3, field_names[1], Price);
      }
      UnknownFields.WriteTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasCloseDate) {
          size += pb::CodedOutputStream.ComputeInt64Size(1, CloseDate);
        }
        if (hasTickerName) {
          size += pb::CodedOutputStream.ComputeStringSize(2, TickerName);
        }
        if (hasPrice) {
          size += pb::CodedOutputStream.ComputeDoubleSize(3, Price);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    public static CurrentCouponResult ParseFrom(pb::ByteString data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static CurrentCouponResult ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static CurrentCouponResult ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    public static CurrentCouponResult ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
    }
    public static CurrentCouponResult ParseFrom(global::System.IO.Stream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static CurrentCouponResult ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    public static CurrentCouponResult ParseDelimitedFrom(global::System.IO.Stream input) {
      return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
    }
    public static CurrentCouponResult ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
      return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
    }
    public static CurrentCouponResult ParseFrom(pb::ICodedInputStream input) {
      return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
    }
    public static CurrentCouponResult ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
    }
    private CurrentCouponResult MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(CurrentCouponResult prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class Builder : pb::GeneratedBuilder<CurrentCouponResult, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(CurrentCouponResult cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private CurrentCouponResult result;
      
      private CurrentCouponResult PrepareBuilder() {
        if (resultIsReadOnly) {
          CurrentCouponResult original = result;
          result = new CurrentCouponResult();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override CurrentCouponResult MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override pbd::MessageDescriptor DescriptorForType {
        get { return global::ccm.quantlib.input.CurrentCouponResult.Descriptor; }
      }
      
      public override CurrentCouponResult DefaultInstanceForType {
        get { return global::ccm.quantlib.input.CurrentCouponResult.DefaultInstance; }
      }
      
      public override CurrentCouponResult BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessage other) {
        if (other is CurrentCouponResult) {
          return MergeFrom((CurrentCouponResult) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(CurrentCouponResult other) {
        if (other == global::ccm.quantlib.input.CurrentCouponResult.DefaultInstance) return this;
        PrepareBuilder();
        if (other.HasCloseDate) {
          CloseDate = other.CloseDate;
        }
        if (other.HasTickerName) {
          TickerName = other.TickerName;
        }
        if (other.HasPrice) {
          Price = other.Price;
        }
        this.MergeUnknownFields(other.UnknownFields);
        return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        pb::UnknownFieldSet.Builder unknownFields = null;
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_currentCouponResultFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _currentCouponResultFieldTags[field_ordinal];
            else {
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                if (unknownFields != null) {
                  this.UnknownFields = unknownFields.Build();
                }
                return this;
              }
              if (unknownFields == null) {
                unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
              }
              ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasCloseDate = input.ReadInt64(ref result.closeDate_);
              break;
            }
            case 18: {
              result.hasTickerName = input.ReadString(ref result.tickerName_);
              break;
            }
            case 25: {
              result.hasPrice = input.ReadDouble(ref result.price_);
              break;
            }
          }
        }
        
        if (unknownFields != null) {
          this.UnknownFields = unknownFields.Build();
        }
        return this;
      }
      
      
      public bool HasCloseDate {
        get { return result.hasCloseDate; }
      }
      public long CloseDate {
        get { return result.CloseDate; }
        set { SetCloseDate(value); }
      }
      public Builder SetCloseDate(long value) {
        PrepareBuilder();
        result.hasCloseDate = true;
        result.closeDate_ = value;
        return this;
      }
      public Builder ClearCloseDate() {
        PrepareBuilder();
        result.hasCloseDate = false;
        result.closeDate_ = 0L;
        return this;
      }
      
      public bool HasTickerName {
        get { return result.hasTickerName; }
      }
      public string TickerName {
        get { return result.TickerName; }
        set { SetTickerName(value); }
      }
      public Builder SetTickerName(string value) {
        pb::ThrowHelper.ThrowIfNull(value, "value");
        PrepareBuilder();
        result.hasTickerName = true;
        result.tickerName_ = value;
        return this;
      }
      public Builder ClearTickerName() {
        PrepareBuilder();
        result.hasTickerName = false;
        result.tickerName_ = "";
        return this;
      }
      
      public bool HasPrice {
        get { return result.hasPrice; }
      }
      public double Price {
        get { return result.Price; }
        set { SetPrice(value); }
      }
      public Builder SetPrice(double value) {
        PrepareBuilder();
        result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder ClearPrice() {
        PrepareBuilder();
        result.hasPrice = false;
        result.price_ = 0D;
        return this;
      }
    }
    static CurrentCouponResult() {
      object.ReferenceEquals(global::ccm.quantlib.input.Proto.CurrentCouponResult.Descriptor, null);
    }
  }
  
  #endregion
  
}

#endregion Designer generated code
