# Return forecasts generated by the default model
#' @title Generate forecasts for the default submodel model. Other submodels have a separate function.
#'
#' @description
#' \code{PredictDflt} Generate default forecasts based on indicative data from a data frame.
#' The forecasts are added as columns to the data frame. Other submodels are driven by PredictSubmodel.
#'
#' @param d60.spl Spline coefficients for d60ent loans
#' @param delq.spl Spline coefficients for delinquent loans
#' @param data data frame containing indicative data for the loans/pools/replines that we want projections for
#' @param version Model version. Allows flexibility in changing model specifications for different versions.
#'
#' @return
#' List with submodel predictions
#'
#' @examples
#' \dontrun{
#'  PredictDflt(d60.spl=d60.spl, delq.spl=NA, data=ppdata, version="v4.00")
#'  }
#'
PredictDflt_2_old <- function(d0.spl = NA, d30.spl=NA, d60.spl=NA, d90.spl=NA, cure.spl=NA, buyout.spl=NA, data, version="") {
  if (! any(is.na(d0.spl)) ) {
    cat("running d0 mdl", "\n")

    pickD0 = ifelse(data$delMonths == 0, 1, 0)
    d0.seasonals <- SeasonalAdjustment(seasonals = d0.spl$seasonalityMultipliers, months = data$monthBucket)
    d0.mdr <- rep(d0.spl$baselineConstant, times=nrow(data)) * d0.seasonals * d0.spl$adjustmentFactor
    param.d0 <- names(d0.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp"), names(d0.spl))]

    d0.mult.df <- data.frame(matrix(1, nrow = nrow(data), ncol = length(d0.spl[["none"]])+4))
    names(d0.mult.df) <- c(names(d0.spl[["none"]]), "monthsSince1", "monthsSince2", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp")
    # get cumHpi index
    a <- unlist(d0.spl["cumHpiIndexInterp"][[1]][1])
    b <- unlist(d0.spl["cumHpiIndexInterp"][[1]][2])
    x <- data$fico
    d0.mult.df[, "cumHpiIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d0.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][1])
    b <- unlist(d0.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][2])
    x <- data$fico
    d0.mult.df[, "laggedUnemployChangeSinceStatusIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y

    for (q in param.d0) {
      d0.spl.status  <- d0.spl[[q]]
      d0.mult.status <- rep(1, times=nrow(data))

      if (q == 'none'){
        param.d0.status <- names(d0.spl.status)[-match(c("noFico", "noDti"),
                                                       names(d0.spl.status))]
        d0.mult.df$noFico <- NULL
        d0.mult.df$noDti  <- NULL
      }
      else{
        param.d0.status <- names(d0.spl.status)[-match(c("noFico"),
                                                       names(d0.spl.status))]
      }

      # add data frame for multiplier
      for (p in param.d0.status) {
        idx <- match(p, names(d0.spl.status))
        # don't need to interpolate
        if (p != "cumHpi" & p != "laggedUnemployChangeSinceStatus"){
          a <- unlist(d0.spl.status[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
          b <- unlist(d0.spl.status[idx][[1]][2])
          x <- data[[p]]
          d0.mult.status <- BuildSpline(a=a, b=b, x=x)$y
          if (p == 'dti'){
            d0.mult.status <- ifelse(data$dti == -999, d0.spl.status$noDti, d0.mult.status)
          }
          if (p == "fico"){
            d0.mult.status <- ifelse(data$hasFICOFlag == 0, d0.spl.status$noFico, d0.mult.status)
          }
        }
        # need to interpolate
        else{
          interp = d0.spl.status[p][[1]]$interpAttribute
          n <- length(d0.spl.status[p][[1]]$functions)
          y <- rep(0, times = nrow(data))
          wgt <- rep(0, times = nrow(data))
          interpIdx = d0.mult.df[, interp]
          tmp = rep(0, times = nrow(data))

          a <- unlist(d0.spl.status[p][[1]]$functions[[1]][1])
          b <- unlist(d0.spl.status[p][[1]]$functions[[1]][2])
          x <- data[[p]]
          noFICO <- BuildSpline(a=a, b=b, x=x)$y

          for (i in 2: n){
            a <- unlist(d0.spl.status[p][[1]]$functions[[i]][1])
            b <- unlist(d0.spl.status[p][[1]]$functions[[i]][2])
            x <- data[[p]]
            y <- BuildSpline(a=a, b=b, x=x)$y
            wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
            tmp = tmp + y * wgt
          }
          d0.mult.status <- tmp
          d0.mult.status <- ifelse(data$hasFICOFlag == 1, d0.mult.status, noFICO)
        }
        d0.mult.status <- ifelse(data$reperformingStatus == q, d0.mult.status, 1)
        d0.mdr <- d0.mdr * d0.mult.status
        d0.mult.df[, p] <- d0.mult.df[, p] *  d0.mult.status
      }
    }

    d0.mdr = d0.mdr * pickD0
    d0.mult.df = d0.mult.df * pickD0

    names(d0.mult.df) <- paste("D0", names(d0.mult.df), version, sep="_")

  } else {
    d0.mdr <- NA
  }

  if (! any(is.na(d30.spl)) ) {
    cat("running d30 mdl", "\n")

    pickD30 = ifelse(data$delMonths == 1, 1, 0)
    d30.seasonals <- SeasonalAdjustment(seasonals = d30.spl$seasonalityMultipliers, months = data$monthBucket)
    d30.mdr <- rep(d30.spl$baselineConstant, times=nrow(data)) * d30.seasonals * d30.spl$adjustmentFactor
    param.d30 <- names(d30.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp"), names(d30.spl))]

    d30.mult.df <- data.frame(matrix(1, nrow = nrow(data), ncol = length(d30.spl[["none"]])+2))
    names(d30.mult.df) <- c(names(d30.spl[["none"]]), "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp")
    # get cumHpi index
    a <- unlist(d30.spl["cumHpiIndexInterp"][[1]][1])
    b <- unlist(d30.spl["cumHpiIndexInterp"][[1]][2])
    x <- data$fico
    d30.mult.df[, "cumHpiIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d30.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][1])
    b <- unlist(d30.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][2])
    x <- data$fico
    d30.mult.df[, "laggedUnemployChangeSinceStatusIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y

    for (q in param.d30) {
      d30.spl.status  <- d30.spl[[q]]
      d30.mult.status <- rep(1, times=nrow(data))

      if (q == 'none'){
        param.d30.status <- names(d30.spl.status)[-match(c("noFico", "noDti"),
                                                         names(d30.spl.status))]
        d30.mult.df$noFico <- NULL
        d30.mult.df$noDti  <- NULL
      }
      else{
        param.d30.status <- names(d30.spl.status)[-match(c("noFico"),
                                                         names(d30.spl.status))]
      }

      # add data frame for multiplier
      for (p in param.d30.status) {
        idx <- match(p, names(d30.spl.status))
        # don't need to interpolate
        if (p != "cumHpi" & p != "laggedUnemployChangeSinceStatus"){
          a <- unlist(d30.spl.status[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
          b <- unlist(d30.spl.status[idx][[1]][2])
          x <- data[[p]]
          d30.mult.status <- BuildSpline(a=a, b=b, x=x)$y
          if (p == 'dti'){
            d30.mult.status <- ifelse(data$dti == -999, d30.spl.status$noDti, d30.mult.status)
          }
          if (p == "fico"){
            d30.mult.status <- ifelse(data$hasFICOFlag == 0, d30.spl.status$noFico, d30.mult.status)
          }
        }
        # need to interpolate
        else{
          interp = d30.spl.status[p][[1]]$interpAttribute
          n <- length(d30.spl.status[p][[1]]$functions)
          y <- rep(0, times = nrow(data))
          wgt <- rep(0, times = nrow(data))
          interpIdx = d30.mult.df[, interp]
          tmp = rep(0, times = nrow(data))

          a <- unlist(d30.spl.status[p][[1]]$functions[[1]][1])
          b <- unlist(d30.spl.status[p][[1]]$functions[[1]][2])
          x <- data[[p]]
          noFICO <- BuildSpline(a=a, b=b, x=x)$y

          for (i in 2: n){
            a <- unlist(d30.spl.status[p][[1]]$functions[[i]][1])
            b <- unlist(d30.spl.status[p][[1]]$functions[[i]][2])
            x <- data[[p]]
            y <- BuildSpline(a=a, b=b, x=x)$y
            wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
            tmp = tmp + y * wgt
          }
          d30.mult.status <- tmp
          d30.mult.status <- ifelse(data$hasFICOFlag == 1, d30.mult.status, noFICO)
        }
        d30.mult.status <- ifelse(data$reperformingStatus == q, d30.mult.status, 1)
        d30.mdr <- d30.mdr * d30.mult.status
        d30.mult.df[, p] <- d30.mult.df[, p] *  d30.mult.status
      }
    }

    d30.mdr = d30.mdr * pickD30
    d30.mult.df = d30.mult.df * pickD30

    names(d30.mult.df) <- paste("D30", names(d30.mult.df), version, sep="_")

  } else {
    d30.mdr <- NA
  }

  if (! any(is.na(d60.spl)) ) {
    cat("running d60 mdl", "\n")

    pickD60 = ifelse(data$delMonths == 2, 1, 0)
    d60.seasonals <- SeasonalAdjustment(seasonals = d60.spl$seasonalityMultipliers, months = data$monthBucket)
    d60.mdr <- rep(d60.spl$baselineConstant, times=nrow(data)) * d60.seasonals * d60.spl$adjustmentFactor
    param.d60 <- names(d60.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers", "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp"), names(d60.spl))]

    d60.mult.df <- data.frame(matrix(1, nrow = nrow(data), ncol = length(d60.spl[["none"]])+2))
    names(d60.mult.df) <- c(names(d60.spl[["none"]]), "cumHpiIndexInterp", "laggedUnemployChangeSinceStatusIndexInterp")
    # get cumHpi index
    a <- unlist(d60.spl["cumHpiIndexInterp"][[1]][1])
    b <- unlist(d60.spl["cumHpiIndexInterp"][[1]][2])
    x <- data$fico
    d60.mult.df[, "cumHpiIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d60.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][1])
    b <- unlist(d60.spl["laggedUnemployChangeSinceStatusIndexInterp"][[1]][2])
    x <- data$fico
    d60.mult.df[, "laggedUnemployChangeSinceStatusIndexInterp"] <- BuildSpline(a=a, b=b, x=x)$y

    for (q in param.d60) {
      d60.spl.status  <- d60.spl[[q]]
      d60.mult.status <- rep(1, times=nrow(data))

      if (q == 'none'){
        param.d60.status <- names(d60.spl.status)[-match(c("noFico", "noDti"),
                                                         names(d60.spl.status))]
        d60.mult.df$noFico <- NULL
        d60.mult.df$noDti  <- NULL
      }
      else{
        param.d60.status <- names(d60.spl.status)
      }

      # add data frame for multiplier
      for (p in param.d60.status) {
        idx <- match(p, names(d60.spl.status))
        # don't need to interpolate
        if (p != "cumHpi" & p != "laggedUnemployChangeSinceStatus"){
          a <- unlist(d60.spl.status[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
          b <- unlist(d60.spl.status[idx][[1]][2])
          x <- data[[p]]
          d60.mult.status <- BuildSpline(a=a, b=b, x=x)$y
          if (p == 'dti'){
            d60.mult.status <- ifelse(data$dti == -999, d60.spl.status$noDti, d60.mult.status)
          }
          if (p == "fico"){
            d60.mult.status <- ifelse(data$hasFICOFlag == 0, d60.spl.status$noFico, d60.mult.status)
          }
        }
        # need to interpolate
        else{
          interp = d60.spl.status[p][[1]]$interpAttribute
          n <- length(d60.spl.status[p][[1]]$functions)
          y <- rep(0, times = nrow(data))
          wgt <- rep(0, times = nrow(data))
          interpIdx = d60.mult.df[, interp]
          tmp = rep(0, times = nrow(data))

          a <- unlist(d60.spl.status[p][[1]]$functions[[1]][1])
          b <- unlist(d60.spl.status[p][[1]]$functions[[1]][2])
          x <- data[[p]]
          noFICO <- BuildSpline(a=a, b=b, x=x)$y

          for (i in 2: n){
            a <- unlist(d60.spl.status[p][[1]]$functions[[i]][1])
            b <- unlist(d60.spl.status[p][[1]]$functions[[i]][2])
            x <- data[[p]]
            y <- BuildSpline(a=a, b=b, x=x)$y
            wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
            tmp = tmp + y * wgt
          }
          d60.mult.status <- tmp
          d60.mult.status <- ifelse(data$hasFICOFlag == 1, d60.mult.status, noFICO)
        }
        d60.mult.status <- ifelse(data$reperformingStatus == q, d60.mult.status, 1)
        d60.mdr <- d60.mdr * d60.mult.status
        d60.mult.df[, p] <- d60.mult.df[, p] *  d60.mult.status
      }
    }

    d60.mdr = d60.mdr * pickD60
    d60.mult.df = d60.mult.df * pickD60

    names(d60.mult.df) <- paste("D60", names(d60.mult.df), version, sep="_")
  } else {
    d60.mdr <- NA
  }

  if (! any(is.na(d90.spl)) ) {
    cat("running d90 mdl\n")

    pickD90 = ifelse(data$delMonths == 3, 1, 0)
    param.d90 <- names(d90.spl)[-match(c("baselineConstant", "adjustmentFactor"),
                                       names(d90.spl))]
    d90.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.d90)))
    names(d90.mult.df) <- param.d90
    d90.mdr <- rep(d90.spl$baselineConstant, times=nrow(data))

    for (p in param.d90) {

      idx <- match(p, names(d90.spl))
      a <- unlist(d90.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
      b <- unlist(d90.spl[idx][[1]][2])
      x <- data[[p]]
      d90.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
      d90.mdr <- d90.mdr * d90.mult.df[, p]
    }

    d90.mdr = d90.mdr * pickD90
    d90.mult.df = d90.mult.df * pickD90

    names(d90.mult.df) <- paste(paste("D90", names(d90.mult.df), sep="_"), version, sep="_")

  } else {
    d90.mdr <- NA
  }

  if (! any(is.na(cure.spl)) ) {
    cat("running cure mdl\n")

    pickD90 = ifelse(data$delMonths == 3, 1, 0)
    param.cure <- names(cure.spl)[-match(c("baselineConstant", "adjustmentFactor"),
                                         names(cure.spl))]
    cure.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.cure)))
    names(cure.mult.df) <- param.cure
    cure.mdr <- rep(cure.spl$baselineConstant, times=nrow(data))
    stay.mdr <- rep(cure.spl$baselineConstant, times=nrow(data))

    for (p in param.cure) {

      idx <- match(p, names(cure.spl))
      a <- unlist(cure.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
      b <- unlist(cure.spl[idx][[1]][2])
      x <- data[[p]]
      cure.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
      cure.mdr <- cure.mdr * cure.mult.df[, p]
    }
    stay.mdr <- 1 - cure.mdr

    cure.mdr = cure.mdr * pickD90
    stay.mdr = stay.mdr * pickD90
    cure.mult.df = cure.mult.df * pickD90

    names(cure.mult.df) <- paste(paste("CURE", names(cure.mult.df), sep="_"), version, sep="_")

  } else {
    cure.mdr <- NA
  }

  if (! any(is.na(buyout.spl)) ) {
    cat("running buyout mdl\n")

    buyout.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=4))
    names(buyout.mult.df) <- c("servicerBuyoutIndex", "buyoutIncentiveShift", "BuyoutLowMult", "BuyoutHighMult")
    buyout.mdr <- rep(1, length(data))
    buyout.submdl <- buyout.spl$buyoutIncentive$functions

    # Get index interp
    aServicer <- unlist(buyout.spl["servicerBuyoutIndexInterp"][[1]][1])
    bServicer <- unlist(buyout.spl["servicerBuyoutIndexInterp"][[1]][2])
    xServicer <- data[["servicerBuyoutIndex"]]
    buyout.mult.df[, "servicerBuyoutIndex"] <- BuildSpline(a=aServicer, b=bServicer, x=xServicer)$y

    # Elbow shift
    aElbow <- unlist(buyout.spl["servicerBuyoutIndexElbow"][[1]][1])
    bElbow <- unlist(buyout.spl["servicerBuyoutIndexElbow"][[1]][2])
    xElbow <- buyout.mult.df[["servicerBuyoutIndex"]]
    buyout.mult.df[, "buyoutIncentiveShift"] <- BuildSpline(a=aElbow, b=bElbow, x=xElbow)$y

    #Buyout Incentive
    x <- data[["buyoutIncentive"]] + buyout.mult.df[["buyoutIncentiveShift"]]

    # Buyout 0 curve
    aLow <- unlist(buyout.submdl[[1]][1])
    bLow <- unlist(buyout.submdl[[1]][2])
    buyout.mult.df[, "BuyoutLowMult"] <- BuildSpline(a=aLow, b=bLow, x=x)$y

    #Buyout 100 curve
    aHigh <- unlist(buyout.submdl[[2]][1])
    bHigh <- unlist(buyout.submdl[[2]][2])
    buyout.mult.df[, "BuyoutHighMult"] <- BuildSpline(a=aHigh, b=bHigh, x=x)$y

    buyout.mdr <- buyout.mult.df[["BuyoutLowMult"]] * (1 - buyout.mult.df[["servicerBuyoutIndex"]]) + buyout.mult.df[["BuyoutHighMult"]] * buyout.mult.df[["servicerBuyoutIndex"]]

  } else {
    buyout.mdr <- NA
  }

  if ( any(is.na(d0.spl)) | any(is.na(d30.spl)) | any(is.na(d60.spl)) | any(is.na(d90.spl)) | any(is.na(cure.spl)) | any(is.na(buyout.spl)) ) {
    all.mdr <- NA
    return(list("pred"=cure.mdr, "mult"=cure.mult.df))
  } else {
    all.mdr <- (d0.mdr + d30.mdr + d60.mdr + d90.mdr + stay.mdr) * buyout.mdr
    transit.mdr <- d0.mdr + d30.mdr + d60.mdr + d90.mdr + stay.mdr
    mult.df <- c(d0.mult.df, d30.mult.df, d60.mult.df, d90.mult.df, stay.mdr, buyout.mult.df)
    # return(list("pred_all"=all.mdr, "pred_d0"=d0.mdr, "pred_d30"=d30.mdr, "pred_d60"=d60.mdr, "pred_stay"=stay.mdr,
    #             "pred_d90"=d90.mdr, "pred_transition"=transit.mdr, "pred_buyout"=buyout.mdr, "mult"=mult.df))
    return(list("pred_all"=all.mdr, "pred_transition"=transit.mdr, "pred_buyout"=buyout.mdr))
  }


}
