# Return forecasts generated by the default model
#' @title Generate forecasts for the default submodel model. Other submodels have a separate function.
#' 
#' @description
#' \code{PredictDflt} Generate default forecasts based on indicative data from a data frame.
#' The forecasts are added as columns to the data frame. Other submodels are driven by PredictSubmodel.
#'  
#' @param curr.spl Spline coefficients for current loans
#' @param delq.spl Spline coefficients for delinquent loans
#' @param data data frame containing indicative data for the loans/pools/replines that we want projections for
#' @param version Model version. Allows flexibility in changing model specifications for different versions.
#' 
#' @return 
#' List with submodel predictions
#' 
#' @examples
#' \dontrun{
#'  PredictDflt(curr.spl=curr.spl, delq.spl=NA, data=ppdata, version="v4.00")
#'  }
#'  
PredictDflt <- function(curr.spl=NA, delq.spl=NA, data, version="") {
  
  if (! any(is.na(curr.spl)) ) {
    param.curr <- names(curr.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers"), 
                                         names(curr.spl))]
    curr.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.curr)))
    names(curr.mult.df) <- param.curr
    
    curr.mdr <- rep(curr.spl$baselineConstant, times=nrow(data))
    
    for (p in param.curr) {
      idx <- match(p, names(curr.spl))
      a <- unlist(curr.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
      b <- unlist(curr.spl[idx][[1]][2]) 
      x <- data[, p]
      curr.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
      curr.mdr <- curr.mdr * curr.mult.df[, p]
    }
    
    names(curr.mult.df) <- paste(paste("dfltcurr", names(curr.mult.df), sep="_"), version, sep="_")
    
  } else {
    curr.mdr <- NA
  }
    
  if (! any(is.na(delq.spl)) ) {
    param.delq <- names(delq.spl)[-match(c("baselineConstant", "adjustmentFactor", "seasonalityMultipliers"), 
                                         names(delq.spl))]
    delq.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.delq)))
    names(delq.mult.df) <- param.delq
    
    delq.mdr <- rep(delq.spl$baselineConstant, times=nrow(data))
  
    for (p in param.delq) {
       idx <- match(p, names(delq.spl))
       a <- unlist(delq.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
       b <- unlist(delq.spl[idx][[1]][2]) 
       x <- data[, p]
       delq.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
       delq.mdr <- delq.mdr * delq.mult.df[, p]
    }
    
    names(delq.mult.df) <- paste(paste("dfltdelq", names(delq.mult.df), sep="_"), version, sep="_")

  } else {
    delq.mdr <- NA
  }
  
  if ( any(is.na(curr.spl)) | any(is.na(delq.spl)) ) {
    all.mdr <- NA
    return(list("pred_all"=all.mdr, "pred_curr"=curr.mdr, "pred_delq"=delq.mdr))
  } else {
      all.mdr <- (delq.mdr * data$pct_dq/100) + curr.mdr * (1 - data$pct_dq/100)
      mult.df <- c(curr.mult.df, delq.mult.df)
      return(list("pred_all"=all.mdr, "pred_curr"=curr.mdr, "pred_delq"=delq.mdr, "mult"=mult.df))
  } 
    
  
}