# Return forecasts generated by the default model
#' @title Generate forecasts for the default submodel model. Other submodels have a separate function.
#'
#' @description
#' \code{PredictDflt} Generate default forecasts based on indicative data from a data frame.
#' The forecasts are added as columns to the data frame. Other submodels are driven by PredictSubmodel.
#'
#' @param d60.spl Spline coefficients for d60ent loans
#' @param delq.spl Spline coefficients for delinquent loans
#' @param data data frame containing indicative data for the loans/pools/replines that we want projections for
#' @param version Model version. Allows flexibility in changing model specifications for different versions.
#'
#' @return
#' List with submodel predictions
#'
#' @examples
#' \dontrun{
#'  PredictDflt(d60.spl=d60.spl, delq.spl=NA, data=ppdata, version="v4.00")
#'  }
#'
PredictDflt_1 <- function(d0.spl = NA, d30.spl=NA, d60.spl=NA, d90.spl=NA, buyout.spl=NA, data, version="") {
  if (! any(is.na(d0.spl)) ) {
    print(paste("running d0 mdl"))
    
    pickD0 = ifelse(data$delMonths == 0, 1, 0)
    d0.seasonals <- SeasonalAdjustment(seasonals = d0.spl$seasonalityMultipliers, months = data$monthBucket)
    
    param.d0 <- names(d0.spl)[-match(c("baselineConstant", "adjustmentFactor", "none_noDTI", "none_noFICO", "HMOD_noFICO", "NHMOD_noFICO", "RP_noFICO", "cumHPIIndex_interp", "laggedUnemployChangeSinceStatusIndex_interp", "seasonalityMultipliers"),
                                     names(d0.spl))]
    d0.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.d0) + 2))
    names(d0.mult.df) <- c(param.d0, "cumHPIIndex_interp", "laggedUnemployChangeSinceStatusIndex_interp")
    # get cumHPI index
    a <- unlist(d0.spl["cumHPIIndex_interp"][[1]][1])
    b <- unlist(d0.spl["cumHPIIndex_interp"][[1]][2])
    x <- data$fico
    d0.mult.df[, "cumHPIIndex_interp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d0.spl["laggedUnemployChangeSinceStatusIndex_interp"][[1]][1])
    b <- unlist(d0.spl["laggedUnemployChangeSinceStatusIndex_interp"][[1]][2])
    x <- data$fico
    d0.mult.df[, "laggedUnemployChangeSinceStatusIndex_interp"] <- BuildSpline(a=a, b=b, x=x)$y
    
    d0.mdr <- rep(d0.spl$baselineConstant, times=nrow(data)) * d0.seasonals
    
    for (p in param.d0) {
      print(paste("running", p))
      
      paramName = unlist(strsplit(p, "_"))
      rp = paramName[1]
      q = paramName[2]
      idx <- match(p, names(d0.spl))
      # don't need to interpolate
      if (!("cumHPI" %in% paramName) & !("laggedUnemployChangeSinceStatus" %in% paramName)){
        a <- unlist(d0.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
        b <- unlist(d0.spl[idx][[1]][2])
        x <- data[[q]]
        d0.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
        d0.mult.df[, p] <- ifelse(data$reperformingStatus %in% paramName, d0.mult.df[, p], 1)
        
        if ("dti" %in% paramName){
          d0.mult.df[, p] <- ifelse(data$dti == -999 & data$reperformingStatus %in% paramName, d0.spl[paste(rp, "noDTI", sep = "_")][[1]], d0.mult.df[, p])
        }
        if ("fico" %in% paramName){
          d0.mult.df[, p] <- ifelse(data$fico == -999 & data$reperformingStatus %in% paramName, d0.spl[paste(rp, "noFICO", sep = "_")][[1]], d0.mult.df[, p])
        }
      }
      # need to interpolate
      else{
        interp = d0.spl[p][[1]]$attribute
        n <- length(d0.spl[p][[1]]$functions)
        y <- rep(0, times = nrow(data))
        wgt <- rep(0, times = nrow(data))
        interpIdx = d0.mult.df[, interp]
        # wgtSpl <- data.frame(cbind(y, wgt, interpIdx))
        tmp = rep(0, times = nrow(data))
        
        a <- unlist(d0.spl[p][[1]]$functions[[1]][1])
        b <- unlist(d0.spl[p][[1]]$functions[[1]][2])
        x <- data[[q]]
        noFICO <- BuildSpline(a=a, b=b, x=x)$y
        
        for (i in 2: n){
          a <- unlist(d0.spl[p][[1]]$functions[[i]][1])
          b <- unlist(d0.spl[p][[1]]$functions[[i]][2])
          x <- data[[q]]
          y <- BuildSpline(a=a, b=b, x=x)$y
          wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
          tmp = tmp + y * wgt
        }
        d0.mult.df[, p] <- tmp
        d0.mult.df[, p] <- ifelse(data$reperformingStatus %in% paramName, d0.mult.df[, p], 1)
        d0.mult.df[, p] <- ifelse(data$fico != -999 | !data$reperformingStatus %in% paramName, d0.mult.df[, p], noFICO)
      }
      
      d0.mdr <- d0.mdr * d0.mult.df[, p]
    }
    
    d0.mdr = d0.mdr * pickD0
    d0.mult.df = d0.mult.df * pickD0
    
    names(d0.mult.df) <- paste(paste("dfltd0", names(d0.mult.df), sep="_"), version, sep="_")
    
  } else {
    d0.mdr <- NA
  }
  
  if (! any(is.na(d30.spl)) ) {
    print(paste("running d30 mdl"))
    
    pickD30 = ifelse(data$delMonths == 1, 1, 0)
    d30.seasonals <- SeasonalAdjustment(seasonals = d30.spl$seasonalityMultipliers, months = data$monthBucket)
    
    param.d30 <- names(d30.spl)[-match(c("baselineConstant", "adjustmentFactor", "none_noDTI", "none_noFICO", "HMOD_noFICO", "NHMOD_noFICO", "RP_noFICO", "cumHPIIndex_interp", "laggedUnemployChangeSinceStatusIndex_interp", "seasonalityMultipliers"),
                                       names(d30.spl))]
    d30.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.d30) + 2))
    names(d30.mult.df) <- c(param.d30, "cumHPIIndex_interp", "laggedUnemployChangeSinceStatusIndex_interp")
    # get cumHPI index
    a <- unlist(d30.spl["cumHPIIndex_interp"][[1]][1])
    b <- unlist(d30.spl["cumHPIIndex_interp"][[1]][2])
    x <- data$fico
    d30.mult.df[, "cumHPIIndex_interp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d30.spl["laggedUnemployChangeSinceStatusIndex_interp"][[1]][1])
    b <- unlist(d30.spl["laggedUnemployChangeSinceStatusIndex_interp"][[1]][2])
    x <- data$fico
    d30.mult.df[, "laggedUnemployChangeSinceStatusIndex_interp"] <- BuildSpline(a=a, b=b, x=x)$y
    
    d30.mdr <- rep(d30.spl$baselineConstant, times=nrow(data)) * d30.seasonals
    
    for (p in param.d30) {
      print(paste("running", p))
      
      paramName = unlist(strsplit(p, "_"))
      rp = paramName[1]
      q = paramName[2]
      idx <- match(p, names(d30.spl))
      # don't need to interpolate
      if (!("cumHPI" %in% paramName) & !("laggedUnemployChangeSinceStatus" %in% paramName)){
        a <- unlist(d30.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
        b <- unlist(d30.spl[idx][[1]][2])
        x <- data[[q]]
        d30.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
        
        d30.mult.df[, p] <- ifelse(data$reperformingStatus %in% paramName, d30.mult.df[, p], 1)
        
        if ("dti" %in% paramName){
          d30.mult.df[, p] <- ifelse(data$dti == -999 & data$reperformingStatus %in% paramName, d30.spl[paste(rp, "noDTI", sep = "_")][[1]], d30.mult.df[, p])
        }
        if ("fico" %in% paramName){
          d30.mult.df[, p] <- ifelse(data$fico == -999 & data$reperformingStatus %in% paramName, d30.spl[paste(rp, "noFICO", sep = "_")][[1]], d30.mult.df[, p])
        }
      }
      # need to interpolate
      else{
        interp = d30.spl[p][[1]]$attribute
        n <- length(d30.spl[p][[1]]$functions)
        y <- rep(0, times = nrow(data))
        wgt <- rep(0, times = nrow(data))
        interpIdx = d30.mult.df[, interp]
        # wgtSpl <- data.frame(cbind(y, wgt, interpIdx))
        tmp = rep(0, times = nrow(data))
        
        a <- unlist(d30.spl[p][[1]]$functions[[1]][1])
        b <- unlist(d30.spl[p][[1]]$functions[[1]][2])
        x <- data[[q]]
        noFICO <- BuildSpline(a=a, b=b, x=x)$y
        
        for (i in 2: n){
          a <- unlist(d30.spl[p][[1]]$functions[[i]][1])
          b <- unlist(d30.spl[p][[1]]$functions[[i]][2])
          x <- data[[q]]
          y <- BuildSpline(a=a, b=b, x=x)$y
          wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
          tmp = tmp + y * wgt
        }
        d30.mult.df[, p] <- tmp
        d30.mult.df[, p] <- ifelse(data$reperformingStatus %in% paramName, d30.mult.df[, p], 1)
        d30.mult.df[, p] <- ifelse(data$fico != -999 | !data$reperformingStatus %in% paramName, d30.mult.df[, p], noFICO)
      }
      
      d30.mdr <- d30.mdr * d30.mult.df[, p]
    }
    
    d30.mdr = d30.mdr * pickD30
    d30.mult.df = d30.mult.df * pickD30
    
    names(d30.mult.df) <- paste(paste("dfltd30", names(d30.mult.df), sep="_"), version, sep="_")
    
  } else {
    d30.mdr <- NA
  }
  
  if (! any(is.na(d60.spl)) ) {
    print(paste("running d60 mdl"))
    
    pickD60 = ifelse(data$delMonths == 2, 1, 0)
    d60.seasonals <- SeasonalAdjustment(seasonals = d60.spl$seasonalityMultipliers, months = data$monthBucket)
    
    param.d60 <- names(d60.spl)[-match(c("baselineConstant", "adjustmentFactor", "none_noDTI", "none_noFICO", "cumHPIIndex_interp", "laggedUnemployChangeSinceStatusIndex_interp", "seasonalityMultipliers"),
                                       names(d60.spl))]
    d60.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.d60) + 2))
    names(d60.mult.df) <- c(param.d60, "cumHPIIndex_interp", "laggedUnemployChangeSinceStatusIndex_interp")
    # get cumHPI index
    a <- unlist(d60.spl["cumHPIIndex_interp"][[1]][1])
    b <- unlist(d60.spl["cumHPIIndex_interp"][[1]][2])
    x <- data$fico
    d60.mult.df[, "cumHPIIndex_interp"] <- BuildSpline(a=a, b=b, x=x)$y
    # get laggedUnemployChangeSinceStatus index
    a <- unlist(d60.spl["laggedUnemployChangeSinceStatusIndex_interp"][[1]][1])
    b <- unlist(d60.spl["laggedUnemployChangeSinceStatusIndex_interp"][[1]][2])
    x <- data$fico
    d60.mult.df[, "laggedUnemployChangeSinceStatusIndex_interp"] <- BuildSpline(a=a, b=b, x=x)$y
    
    d60.mdr <- rep(d60.spl$baselineConstant, times=nrow(data)) * d60.seasonals
    
    for (p in param.d60) {
      print(paste("running", p))
      
      paramName = unlist(strsplit(p, "_"))
      rp = paramName[1]
      q = paramName[2]
      idx <- match(p, names(d60.spl))
      # don't need to interpolate
      if (!("cumHPI" %in% paramName) & !("laggedUnemployChangeSinceStatus" %in% paramName)){
        a <- unlist(d60.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
        b <- unlist(d60.spl[idx][[1]][2])
        x <- data[[q]]
        d60.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
        
        d60.mult.df[, p] <- ifelse(data$reperformingStatus %in% paramName, d60.mult.df[, p], 1)
        
        if ("dti" %in% paramName){
          d60.mult.df[, p] <- ifelse(data$dti == -999 & data$reperformingStatus %in% paramName, d60.spl[paste(rp, "noDTI", sep = "_")][[1]], d60.mult.df[, p])
        }
        if ("fico" %in% paramName){
          d60.mult.df[, p] <- ifelse(data$fico == -999 & data$reperformingStatus %in% paramName, d60.spl[paste(rp, "noFICO", sep = "_")][[1]], d60.mult.df[, p])
        }
      }
      # need to interpolate
      else{
        interp = d60.spl[p][[1]]$attribute
        n <- length(d60.spl[p][[1]]$functions)
        y <- rep(0, times = nrow(data))
        wgt <- rep(0, times = nrow(data))
        interpIdx = d60.mult.df[, interp]
        # wgtSpl <- data.frame(cbind(y, wgt, interpIdx))
        tmp = rep(0, times = nrow(data))
        
        a <- unlist(d60.spl[p][[1]]$functions[[1]][1])
        b <- unlist(d60.spl[p][[1]]$functions[[1]][2])
        x <- data[[q]]
        noFICO <- BuildSpline(a=a, b=b, x=x)$y
        
        for (i in 2: n){
          a <- unlist(d60.spl[p][[1]]$functions[[i]][1])
          b <- unlist(d60.spl[p][[1]]$functions[[i]][2])
          x <- data[[q]]
          y <- BuildSpline(a=a, b=b, x=x)$y
          wgt = ifelse(i!=floor(interpIdx) & i!=floor(interpIdx)+1, 0, ifelse(i==floor(interpIdx), 1 - (interpIdx - floor(interpIdx)), interpIdx - floor(interpIdx)))
          tmp = tmp + y * wgt
        }
        d60.mult.df[, p] <- tmp
        d60.mult.df[, p] <- ifelse(data$reperformingStatus %in% paramName, d60.mult.df[, p], 1)
        d60.mult.df[, p] <- ifelse(data$fico != -999 | !data$reperformingStatus %in% paramName, d60.mult.df[, p], noFICO)
      }
      
      d60.mdr <- d60.mdr * d60.mult.df[, p]
    }
    
    d60.mdr = d60.mdr * pickD60
    d60.mult.df = d60.mult.df * pickD60
    
    names(d60.mult.df) <- paste(paste("dfltd60", names(d60.mult.df), sep="_"), version, sep="_")
  } else {
    d60.mdr <- NA
  }
  
  if (! any(is.na(d90.spl)) ) {
    print(paste("running d90 mdl"))
    
    pickD90 = ifelse(data$delMonths > 2, 1, 0)
    param.d90 <- names(d90.spl)[-match(c("baselineConstant", "adjustmentFactor"),
                                       names(d90.spl))]
    d90.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=length(param.d90)))
    names(d90.mult.df) <- param.d90
    d90.mdr <- rep(d90.spl$baselineConstant, times=nrow(data))
    
    for (p in param.d90) {
      print(paste("running", p))
      
      idx <- match(p, names(d90.spl))
      a <- unlist(d90.spl[idx][[1]][1]) # Otherwise R complains about not being able to coerce a list into a double
      b <- unlist(d90.spl[idx][[1]][2])
      x <- data[[p]]
      d90.mult.df[, p] <- BuildSpline(a=a, b=b, x=x)$y
      d90.mdr <- d90.mdr * d90.mult.df[, p]
    }
    
    d90.mdr = d90.mdr * pickD90
    d90.mult.df = d90.mult.df * pickD90
    
    names(d90.mult.df) <- paste(paste("dfltd90", names(d90.mult.df), sep="_"), version, sep="_")
    
  } else {
    d90.mdr <- NA
  }
  
  if (! any(is.na(buyout.spl)) ) {
    print(paste("running buyout mdl"))

    buyout.mult.df <- data.frame(matrix(nrow=nrow(data), ncol=4))
    names(buyout.mult.df) <- c("servicerBuyoutIndex", "buyoutIncentiveShift", "BuyoutLowMult", "BuyoutHighMult")
    buyout.mdr <- rep(1, length(data))
    buyout.submdl <- buyout.spl$buyoutIncentive$functions

    # Get index interp
    aServicer <- unlist(buyout.spl["servicerBuyoutIndex_interp"][[1]][1])
    bServicer <- unlist(buyout.spl["servicerBuyoutIndex_interp"][[1]][2])
    xServicer <- data[["servicerBuyoutIndex"]]
    buyout.mult.df[, "servicerBuyoutIndex"] <- BuildSpline(a=aServicer, b=bServicer, x=xServicer)$y

    # Elbow shift
    aElbow <- unlist(buyout.spl["elbow_servicerBuyoutIndex"][[1]][1])
    bElbow <- unlist(buyout.spl["elbow_servicerBuyoutIndex"][[1]][2])
    xElbow <- buyout.mult.df[["servicerBuyoutIndex"]]
    buyout.mult.df[, "buyoutIncentiveShift"] <- BuildSpline(a=aElbow, b=bElbow, x=xElbow)$y

    #Buyout Incentive
    x <- data[["buyoutIncentive"]] + buyout.mult.df[["buyoutIncentiveShift"]]

    # Buyout 0 curve
    aLow <- unlist(buyout.submdl[[1]][1])
    bLow <- unlist(buyout.submdl[[1]][2])
    buyout.mult.df[, "BuyoutLowMult"] <- BuildSpline(a=aLow, b=bLow, x=x)$y

    #Buyout 100 curve
    aHigh <- unlist(buyout.submdl[[2]][1])
    bHigh <- unlist(buyout.submdl[[2]][2])
    buyout.mult.df[, "BuyoutHighMult"] <- BuildSpline(a=aHigh, b=bHigh, x=x)$y

    buyout.mdr <- buyout.mult.df[["BuyoutLowMult"]] * (1 - buyout.mult.df[["servicerBuyoutIndex"]]) + buyout.mult.df[["BuyoutHighMult"]] * buyout.mult.df[["servicerBuyoutIndex"]]

  } else {
    buyout.mdr <- NA
  }
  
  if ( any(is.na(d0.spl)) | any(is.na(d30.spl)) | any(is.na(d60.spl)) | any(is.na(d90.spl)) | any(is.na(buyout.spl)) ) {
    all.mdr <- NA
    # return(list("pred_all"=all.mdr, "pred_d0"=d0.mdr, "pred_d30"=d30.mdr, "pred_d60"=d60.mdr, "pred_90"=d90.mdr, "pred_buyout"=buyout.mdr))
    return(list("pred_d60"=d0.mdr, "mult" = d0.mult.df))
  } else {
      all.mdr <- (d0.mdr + d30.mdr + d60.mdr + d90.mdr) * buyout.mdr
      transit.mdr <- d0.mdr + d30.mdr + d60.mdr + d90.mdr
      mult.df <- c(d0.mult.df, d30.mult.df, d60.mult.df, d90.mult.df, buyout.mult.df)
      return(list("pred_all"=all.mdr, "pred_d0"=d0.mdr, "pred_d30"=d30.mdr, "pred_d60"=d60.mdr, "pred_d90"=d90.mdr, "pred_transit"=transit.mdr, "pred_buyout"=buyout.mdr, "mult"=mult.df))
  }
  
  
}
