// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrentCoupon.proto

#ifndef PROTOBUF_CurrentCoupon_2eproto__INCLUDED
#define PROTOBUF_CurrentCoupon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ccm {
namespace quantlib {
namespace input {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CurrentCoupon_2eproto();
void protobuf_AssignDesc_CurrentCoupon_2eproto();
void protobuf_ShutdownFile_CurrentCoupon_2eproto();

class CurrentCoupon;
class CurrentCoupon_TBA;

// ===================================================================

class CurrentCoupon_TBA : public ::google::protobuf::Message {
 public:
  CurrentCoupon_TBA();
  virtual ~CurrentCoupon_TBA();

  CurrentCoupon_TBA(const CurrentCoupon_TBA& from);

  inline CurrentCoupon_TBA& operator=(const CurrentCoupon_TBA& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CurrentCoupon_TBA& default_instance();

  void Swap(CurrentCoupon_TBA* other);

  // implements Message ----------------------------------------------

  CurrentCoupon_TBA* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CurrentCoupon_TBA& from);
  void MergeFrom(const CurrentCoupon_TBA& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string ticker_name = 1;
  inline bool has_ticker_name() const;
  inline void clear_ticker_name();
  static const int kTickerNameFieldNumber = 1;
  inline const ::std::string& ticker_name() const;
  inline void set_ticker_name(const ::std::string& value);
  inline void set_ticker_name(const char* value);
  inline void set_ticker_name(const char* value, size_t size);
  inline ::std::string* mutable_ticker_name();
  inline ::std::string* release_ticker_name();
  inline void set_allocated_ticker_name(::std::string* ticker_name);

  // required double price = 2;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 2;
  inline double price() const;
  inline void set_price(double value);

  // required int64 settle_date = 3;
  inline bool has_settle_date() const;
  inline void clear_settle_date();
  static const int kSettleDateFieldNumber = 3;
  inline ::google::protobuf::int64 settle_date() const;
  inline void set_settle_date(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ccm.quantlib.input.CurrentCoupon.TBA)
 private:
  inline void set_has_ticker_name();
  inline void clear_has_ticker_name();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_settle_date();
  inline void clear_has_settle_date();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* ticker_name_;
  double price_;
  ::google::protobuf::int64 settle_date_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_CurrentCoupon_2eproto();
  friend void protobuf_AssignDesc_CurrentCoupon_2eproto();
  friend void protobuf_ShutdownFile_CurrentCoupon_2eproto();

  void InitAsDefaultInstance();
  static CurrentCoupon_TBA* default_instance_;
};
// -------------------------------------------------------------------

class CurrentCoupon : public ::google::protobuf::Message {
 public:
  CurrentCoupon();
  virtual ~CurrentCoupon();

  CurrentCoupon(const CurrentCoupon& from);

  inline CurrentCoupon& operator=(const CurrentCoupon& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CurrentCoupon& default_instance();

  void Swap(CurrentCoupon* other);

  // implements Message ----------------------------------------------

  CurrentCoupon* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CurrentCoupon& from);
  void MergeFrom(const CurrentCoupon& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef CurrentCoupon_TBA TBA;

  // accessors -------------------------------------------------------

  // required int64 close_date = 1;
  inline bool has_close_date() const;
  inline void clear_close_date();
  static const int kCloseDateFieldNumber = 1;
  inline ::google::protobuf::int64 close_date() const;
  inline void set_close_date(::google::protobuf::int64 value);

  // repeated .ccm.quantlib.input.CurrentCoupon.TBA tba = 100;
  inline int tba_size() const;
  inline void clear_tba();
  static const int kTbaFieldNumber = 100;
  inline const ::ccm::quantlib::input::CurrentCoupon_TBA& tba(int index) const;
  inline ::ccm::quantlib::input::CurrentCoupon_TBA* mutable_tba(int index);
  inline ::ccm::quantlib::input::CurrentCoupon_TBA* add_tba();
  inline const ::google::protobuf::RepeatedPtrField< ::ccm::quantlib::input::CurrentCoupon_TBA >&
      tba() const;
  inline ::google::protobuf::RepeatedPtrField< ::ccm::quantlib::input::CurrentCoupon_TBA >*
      mutable_tba();

  // @@protoc_insertion_point(class_scope:ccm.quantlib.input.CurrentCoupon)
 private:
  inline void set_has_close_date();
  inline void clear_has_close_date();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 close_date_;
  ::google::protobuf::RepeatedPtrField< ::ccm::quantlib::input::CurrentCoupon_TBA > tba_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_CurrentCoupon_2eproto();
  friend void protobuf_AssignDesc_CurrentCoupon_2eproto();
  friend void protobuf_ShutdownFile_CurrentCoupon_2eproto();

  void InitAsDefaultInstance();
  static CurrentCoupon* default_instance_;
};
// ===================================================================


// ===================================================================

// CurrentCoupon_TBA

// required string ticker_name = 1;
inline bool CurrentCoupon_TBA::has_ticker_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CurrentCoupon_TBA::set_has_ticker_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CurrentCoupon_TBA::clear_has_ticker_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CurrentCoupon_TBA::clear_ticker_name() {
  if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
    ticker_name_->clear();
  }
  clear_has_ticker_name();
}
inline const ::std::string& CurrentCoupon_TBA::ticker_name() const {
  return *ticker_name_;
}
inline void CurrentCoupon_TBA::set_ticker_name(const ::std::string& value) {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  ticker_name_->assign(value);
}
inline void CurrentCoupon_TBA::set_ticker_name(const char* value) {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  ticker_name_->assign(value);
}
inline void CurrentCoupon_TBA::set_ticker_name(const char* value, size_t size) {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  ticker_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CurrentCoupon_TBA::mutable_ticker_name() {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  return ticker_name_;
}
inline ::std::string* CurrentCoupon_TBA::release_ticker_name() {
  clear_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ticker_name_;
    ticker_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CurrentCoupon_TBA::set_allocated_ticker_name(::std::string* ticker_name) {
  if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
    delete ticker_name_;
  }
  if (ticker_name) {
    set_has_ticker_name();
    ticker_name_ = ticker_name;
  } else {
    clear_has_ticker_name();
    ticker_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required double price = 2;
inline bool CurrentCoupon_TBA::has_price() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CurrentCoupon_TBA::set_has_price() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CurrentCoupon_TBA::clear_has_price() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CurrentCoupon_TBA::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline double CurrentCoupon_TBA::price() const {
  return price_;
}
inline void CurrentCoupon_TBA::set_price(double value) {
  set_has_price();
  price_ = value;
}

// required int64 settle_date = 3;
inline bool CurrentCoupon_TBA::has_settle_date() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CurrentCoupon_TBA::set_has_settle_date() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CurrentCoupon_TBA::clear_has_settle_date() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CurrentCoupon_TBA::clear_settle_date() {
  settle_date_ = GOOGLE_LONGLONG(0);
  clear_has_settle_date();
}
inline ::google::protobuf::int64 CurrentCoupon_TBA::settle_date() const {
  return settle_date_;
}
inline void CurrentCoupon_TBA::set_settle_date(::google::protobuf::int64 value) {
  set_has_settle_date();
  settle_date_ = value;
}

// -------------------------------------------------------------------

// CurrentCoupon

// required int64 close_date = 1;
inline bool CurrentCoupon::has_close_date() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CurrentCoupon::set_has_close_date() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CurrentCoupon::clear_has_close_date() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CurrentCoupon::clear_close_date() {
  close_date_ = GOOGLE_LONGLONG(0);
  clear_has_close_date();
}
inline ::google::protobuf::int64 CurrentCoupon::close_date() const {
  return close_date_;
}
inline void CurrentCoupon::set_close_date(::google::protobuf::int64 value) {
  set_has_close_date();
  close_date_ = value;
}

// repeated .ccm.quantlib.input.CurrentCoupon.TBA tba = 100;
inline int CurrentCoupon::tba_size() const {
  return tba_.size();
}
inline void CurrentCoupon::clear_tba() {
  tba_.Clear();
}
inline const ::ccm::quantlib::input::CurrentCoupon_TBA& CurrentCoupon::tba(int index) const {
  return tba_.Get(index);
}
inline ::ccm::quantlib::input::CurrentCoupon_TBA* CurrentCoupon::mutable_tba(int index) {
  return tba_.Mutable(index);
}
inline ::ccm::quantlib::input::CurrentCoupon_TBA* CurrentCoupon::add_tba() {
  return tba_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ccm::quantlib::input::CurrentCoupon_TBA >&
CurrentCoupon::tba() const {
  return tba_;
}
inline ::google::protobuf::RepeatedPtrField< ::ccm::quantlib::input::CurrentCoupon_TBA >*
CurrentCoupon::mutable_tba() {
  return &tba_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace input
}  // namespace quantlib
}  // namespace ccm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CurrentCoupon_2eproto__INCLUDED
