// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrentCouponResult.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CurrentCouponResult.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ccm {
namespace quantlib {
namespace input {

namespace {

const ::google::protobuf::Descriptor* CurrentCouponResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CurrentCouponResult_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CurrentCouponResult_2eproto() {
  protobuf_AddDesc_CurrentCouponResult_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CurrentCouponResult.proto");
  GOOGLE_CHECK(file != NULL);
  CurrentCouponResult_descriptor_ = file->message_type(0);
  static const int CurrentCouponResult_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCouponResult, close_date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCouponResult, ticker_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCouponResult, price_),
  };
  CurrentCouponResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CurrentCouponResult_descriptor_,
      CurrentCouponResult::default_instance_,
      CurrentCouponResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCouponResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CurrentCouponResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CurrentCouponResult));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CurrentCouponResult_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CurrentCouponResult_descriptor_, &CurrentCouponResult::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CurrentCouponResult_2eproto() {
  delete CurrentCouponResult::default_instance_;
  delete CurrentCouponResult_reflection_;
}

void protobuf_AddDesc_CurrentCouponResult_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031CurrentCouponResult.proto\022\022ccm.quantli"
    "b.input\"M\n\023CurrentCouponResult\022\022\n\nclose_"
    "date\030\001 \002(\003\022\023\n\013ticker_name\030\002 \002(\t\022\r\n\005price"
    "\030\003 \002(\001B\002H\001", 130);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CurrentCouponResult.proto", &protobuf_RegisterTypes);
  CurrentCouponResult::default_instance_ = new CurrentCouponResult();
  CurrentCouponResult::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CurrentCouponResult_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CurrentCouponResult_2eproto {
  StaticDescriptorInitializer_CurrentCouponResult_2eproto() {
    protobuf_AddDesc_CurrentCouponResult_2eproto();
  }
} static_descriptor_initializer_CurrentCouponResult_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CurrentCouponResult::kCloseDateFieldNumber;
const int CurrentCouponResult::kTickerNameFieldNumber;
const int CurrentCouponResult::kPriceFieldNumber;
#endif  // !_MSC_VER

CurrentCouponResult::CurrentCouponResult()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CurrentCouponResult::InitAsDefaultInstance() {
}

CurrentCouponResult::CurrentCouponResult(const CurrentCouponResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CurrentCouponResult::SharedCtor() {
  _cached_size_ = 0;
  close_date_ = GOOGLE_LONGLONG(0);
  ticker_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  price_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CurrentCouponResult::~CurrentCouponResult() {
  SharedDtor();
}

void CurrentCouponResult::SharedDtor() {
  if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
    delete ticker_name_;
  }
  if (this != default_instance_) {
  }
}

void CurrentCouponResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CurrentCouponResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CurrentCouponResult_descriptor_;
}

const CurrentCouponResult& CurrentCouponResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CurrentCouponResult_2eproto();
  return *default_instance_;
}

CurrentCouponResult* CurrentCouponResult::default_instance_ = NULL;

CurrentCouponResult* CurrentCouponResult::New() const {
  return new CurrentCouponResult;
}

void CurrentCouponResult::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    close_date_ = GOOGLE_LONGLONG(0);
    if (has_ticker_name()) {
      if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
        ticker_name_->clear();
      }
    }
    price_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CurrentCouponResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 close_date = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &close_date_)));
          set_has_close_date();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_ticker_name;
        break;
      }

      // required string ticker_name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ticker_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ticker_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->ticker_name().data(), this->ticker_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(25)) goto parse_price;
        break;
      }

      // required double price = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_price:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &price_)));
          set_has_price();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CurrentCouponResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 close_date = 1;
  if (has_close_date()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->close_date(), output);
  }

  // required string ticker_name = 2;
  if (has_ticker_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ticker_name().data(), this->ticker_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->ticker_name(), output);
  }

  // required double price = 3;
  if (has_price()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->price(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CurrentCouponResult::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 close_date = 1;
  if (has_close_date()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->close_date(), target);
  }

  // required string ticker_name = 2;
  if (has_ticker_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->ticker_name().data(), this->ticker_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->ticker_name(), target);
  }

  // required double price = 3;
  if (has_price()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->price(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CurrentCouponResult::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 close_date = 1;
    if (has_close_date()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->close_date());
    }

    // required string ticker_name = 2;
    if (has_ticker_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ticker_name());
    }

    // required double price = 3;
    if (has_price()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CurrentCouponResult::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CurrentCouponResult* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CurrentCouponResult*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CurrentCouponResult::MergeFrom(const CurrentCouponResult& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_close_date()) {
      set_close_date(from.close_date());
    }
    if (from.has_ticker_name()) {
      set_ticker_name(from.ticker_name());
    }
    if (from.has_price()) {
      set_price(from.price());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CurrentCouponResult::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CurrentCouponResult::CopyFrom(const CurrentCouponResult& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CurrentCouponResult::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void CurrentCouponResult::Swap(CurrentCouponResult* other) {
  if (other != this) {
    std::swap(close_date_, other->close_date_);
    std::swap(ticker_name_, other->ticker_name_);
    std::swap(price_, other->price_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CurrentCouponResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CurrentCouponResult_descriptor_;
  metadata.reflection = CurrentCouponResult_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace input
}  // namespace quantlib
}  // namespace ccm

// @@protoc_insertion_point(global_scope)
