// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrentCouponResult.proto

#ifndef PROTOBUF_CurrentCouponResult_2eproto__INCLUDED
#define PROTOBUF_CurrentCouponResult_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ccm {
namespace quantlib {
namespace input {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CurrentCouponResult_2eproto();
void protobuf_AssignDesc_CurrentCouponResult_2eproto();
void protobuf_ShutdownFile_CurrentCouponResult_2eproto();

class CurrentCouponResult;

// ===================================================================

class CurrentCouponResult : public ::google::protobuf::Message {
 public:
  CurrentCouponResult();
  virtual ~CurrentCouponResult();

  CurrentCouponResult(const CurrentCouponResult& from);

  inline CurrentCouponResult& operator=(const CurrentCouponResult& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CurrentCouponResult& default_instance();

  void Swap(CurrentCouponResult* other);

  // implements Message ----------------------------------------------

  CurrentCouponResult* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CurrentCouponResult& from);
  void MergeFrom(const CurrentCouponResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 close_date = 1;
  inline bool has_close_date() const;
  inline void clear_close_date();
  static const int kCloseDateFieldNumber = 1;
  inline ::google::protobuf::int64 close_date() const;
  inline void set_close_date(::google::protobuf::int64 value);

  // required string ticker_name = 2;
  inline bool has_ticker_name() const;
  inline void clear_ticker_name();
  static const int kTickerNameFieldNumber = 2;
  inline const ::std::string& ticker_name() const;
  inline void set_ticker_name(const ::std::string& value);
  inline void set_ticker_name(const char* value);
  inline void set_ticker_name(const char* value, size_t size);
  inline ::std::string* mutable_ticker_name();
  inline ::std::string* release_ticker_name();
  inline void set_allocated_ticker_name(::std::string* ticker_name);

  // required double price = 3;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 3;
  inline double price() const;
  inline void set_price(double value);

  // @@protoc_insertion_point(class_scope:ccm.quantlib.input.CurrentCouponResult)
 private:
  inline void set_has_close_date();
  inline void clear_has_close_date();
  inline void set_has_ticker_name();
  inline void clear_has_ticker_name();
  inline void set_has_price();
  inline void clear_has_price();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 close_date_;
  ::std::string* ticker_name_;
  double price_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_CurrentCouponResult_2eproto();
  friend void protobuf_AssignDesc_CurrentCouponResult_2eproto();
  friend void protobuf_ShutdownFile_CurrentCouponResult_2eproto();

  void InitAsDefaultInstance();
  static CurrentCouponResult* default_instance_;
};
// ===================================================================


// ===================================================================

// CurrentCouponResult

// required int64 close_date = 1;
inline bool CurrentCouponResult::has_close_date() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CurrentCouponResult::set_has_close_date() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CurrentCouponResult::clear_has_close_date() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CurrentCouponResult::clear_close_date() {
  close_date_ = GOOGLE_LONGLONG(0);
  clear_has_close_date();
}
inline ::google::protobuf::int64 CurrentCouponResult::close_date() const {
  return close_date_;
}
inline void CurrentCouponResult::set_close_date(::google::protobuf::int64 value) {
  set_has_close_date();
  close_date_ = value;
}

// required string ticker_name = 2;
inline bool CurrentCouponResult::has_ticker_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CurrentCouponResult::set_has_ticker_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CurrentCouponResult::clear_has_ticker_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CurrentCouponResult::clear_ticker_name() {
  if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
    ticker_name_->clear();
  }
  clear_has_ticker_name();
}
inline const ::std::string& CurrentCouponResult::ticker_name() const {
  return *ticker_name_;
}
inline void CurrentCouponResult::set_ticker_name(const ::std::string& value) {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  ticker_name_->assign(value);
}
inline void CurrentCouponResult::set_ticker_name(const char* value) {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  ticker_name_->assign(value);
}
inline void CurrentCouponResult::set_ticker_name(const char* value, size_t size) {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  ticker_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CurrentCouponResult::mutable_ticker_name() {
  set_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    ticker_name_ = new ::std::string;
  }
  return ticker_name_;
}
inline ::std::string* CurrentCouponResult::release_ticker_name() {
  clear_has_ticker_name();
  if (ticker_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ticker_name_;
    ticker_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CurrentCouponResult::set_allocated_ticker_name(::std::string* ticker_name) {
  if (ticker_name_ != &::google::protobuf::internal::kEmptyString) {
    delete ticker_name_;
  }
  if (ticker_name) {
    set_has_ticker_name();
    ticker_name_ = ticker_name;
  } else {
    clear_has_ticker_name();
    ticker_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required double price = 3;
inline bool CurrentCouponResult::has_price() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CurrentCouponResult::set_has_price() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CurrentCouponResult::clear_has_price() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CurrentCouponResult::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline double CurrentCouponResult::price() const {
  return price_;
}
inline void CurrentCouponResult::set_price(double value) {
  set_has_price();
  price_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace input
}  // namespace quantlib
}  // namespace ccm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CurrentCouponResult_2eproto__INCLUDED
